ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "accountData" JSONB NOT NULL DEFAULT '{}';
CREATE TABLE IF NOT EXISTS "UserIdentityDocument" (
 "id" TEXT PRIMARY KEY, "userId" TEXT NOT NULL UNIQUE REFERENCES "User"("id") ON DELETE CASCADE,
 "kind" TEXT NOT NULL, "filename" TEXT NOT NULL, "mimeType" TEXT NOT NULL, "sizeBytes" INTEGER NOT NULL,
 "sha256" TEXT NOT NULL, "content" BYTEA NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
