import { CalendarDays, History, Fingerprint, Activity, BookOpen, CalendarClock, ClipboardList, FileCheck2, HeartPulse, Building2, LogOut, MapPin, MessageCircle, ShieldCheck, Stethoscope, UserRound, Users, ChevronDown, KeyRound, type LucideIcon } from 'lucide-react';
const icons: Record<string,LucideIcon> = {'professional-agenda':CalendarDays,utility:Fingerprint,'identification-history':History,record:ClipboardList,medications:CalendarClock,vitals:HeartPulse,diary:BookOpen,consultant:MessageCircle,'family-history':Activity,profiles:Users,insurance:Building2,account:UserRound,clinicar:Stethoscope,'professional-access':KeyRound,'professional-locations':MapPin,professional:FileCheck2,'access-requests':ShieldCheck,'consultation-confirmations':FileCheck2,administration:ShieldCheck};
export function NavigationIcon({destination,className='h-6 w-6'}:{destination:string;className?:string}) {const Icon=icons[destination]??ClipboardList;return <Icon aria-hidden="true" className={className} strokeWidth={1.8}/>;}
const health = [['record','Prontuário'],['medications','Agenda de medicamentos'],['vitals','Sinais vitais'],['diary','Meu Diário'],['consultant','Consultor'],['family-history','Histórico familiar'],['profiles','Perfis e dependentes'],['insurance','Convênios'],['account','Meu cadastro']];
const professional = [['clinicar','Atendimento'],['professional-agenda','Minha agenda'],['professional-access','Solicitar acesso ao prontuário do paciente'],['professional-locations','Locais que atendo'],['professional','Validação de cadastro profissional']];
export default function DashboardNavigation({current,onSelect,onLogout,isProfessional,canPractice,canAdmin,external=true}:{current:string;onSelect:(destination:string)=>void;onLogout:()=>void;isProfessional:boolean;canPractice:boolean;canAdmin:boolean;includeHome?:boolean;external?:boolean}) {
  const tile=(destination:string,label:string,disabled=false)=><button type="button" key={destination} disabled={disabled} title={disabled?'Disponível após aprovação do perfil profissional':undefined} aria-current={current===destination?'page':undefined} onClick={()=>onSelect(destination)} className={`group flex min-h-[112px] min-w-0 flex-col items-start justify-between gap-3 rounded-2xl border p-4 text-left transition-colors focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-moss-700 disabled:cursor-not-allowed disabled:opacity-40 ${current===destination?'border-moss-500 bg-moss-50 text-moss-800':'border-line bg-white text-ink hover:border-moss-500 hover:bg-moss-50'}`}><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-moss-50 text-moss-700 group-hover:bg-white"><NavigationIcon destination={destination}/></span><span className="break-words text-sm font-semibold leading-snug">{label}</span>{disabled&&<span className="text-[11px] font-normal text-mute">Aguardando validação</span>}</button>;
  return <nav aria-label="Menu do MyDoctor" className="space-y-5"><section><h2 className="mb-3 text-xs font-bold uppercase tracking-wide text-mute">Minha saúde</h2><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{health.map(([key,label])=>tile(key,label))}</div></section>{external&&isProfessional&&<details className="group rounded-2xl border border-line bg-white"><summary className="flex cursor-pointer list-none items-center gap-3 p-4 font-bold text-ink"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-moss-50 text-moss-700"><Stethoscope aria-hidden="true" className="h-6 w-6"/></span><span className="flex-1">Profissional</span><ChevronDown aria-hidden="true" className="h-5 w-5 transition-transform group-open:rotate-180"/></summary><div className="border-t border-line p-3 sm:p-4"><div aria-label="Menu profissional" className="grid grid-cols-2 gap-3 lg:grid-cols-4">{professional.map(([key,label])=>tile(key,label,key!=='professional'&&!canPractice))}</div></div></details>}{external&&<section><h2 className="mb-3 text-xs font-bold uppercase tracking-wide text-mute">Utilidade pública</h2><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{tile('utility','Identificar Pessoa')}{tile('account','Cadastrar digital')}{tile('identification-history','Acessos à minha digital')}</div></section>}{external&&<section><h2 className="mb-3 text-xs font-bold uppercase tracking-wide text-mute">Acessos e confirmações</h2><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{tile('access-requests','Solicitações de acesso')}{tile('consultation-confirmations','Atendimentos para confirmar')}{canAdmin&&tile('administration','Administração')}</div></section>}<div className="flex justify-end border-t border-line pt-3"><button type="button" onClick={onLogout} className="inline-flex min-h-11 items-center gap-2 rounded-xl px-4 py-2 text-sm font-semibold text-mute hover:bg-white hover:text-danger-600"><LogOut aria-hidden="true" className="h-4 w-4"/>Sair</button></div></nav>;
}

