import { useEffect, useRef, useState } from 'react';
import { Camera, RotateCcw, X } from 'lucide-react';
export interface PhotoDiagnostic { width:number;height:number;brightness:number;sharpness:number;issues:string[] }
// Diagnóstico fotográfico simples; não extrai digital nem avalia qualidade biométrica.
export function diagnosePhoto(source:HTMLCanvasElement):PhotoDiagnostic{
  const sample=document.createElement('canvas');sample.width=256;sample.height=256;
  const ctx=sample.getContext('2d',{willReadFrequently:true});if(!ctx)throw new Error('Não foi possível avaliar a prévia.');
  ctx.drawImage(source,source.width*.25,source.height*.15,source.width*.5,source.height*.7,0,0,256,256);
  const rgba=ctx.getImageData(0,0,256,256).data,gray=new Float32Array(256*256);let sum=0;
  for(let i=0;i<gray.length;i++){gray[i]=rgba[i*4]*.299+rgba[i*4+1]*.587+rgba[i*4+2]*.114;sum+=gray[i]}
  let lap=0,squared=0,n=0;for(let y=1;y<255;y++)for(let x=1;x<255;x++){const i=y*256+x,v=gray[i-1]+gray[i+1]+gray[i-256]+gray[i+256]-4*gray[i];lap+=v;squared+=v*v;n++}
  const brightness=Math.round(sum/gray.length),sharpness=Math.round(Math.max(0,squared/n-(lap/n)**2));
  const issues:string[]=[];if(Math.min(source.width,source.height)<720)issues.push('Resolução baixa. Tente a câmera traseira em maior resolução.');if(brightness<45)issues.push('Imagem escura. Procure iluminação uniforme.');if(brightness>225)issues.push('Imagem muito clara. Evite reflexos e luz direta.');if(sharpness<35)issues.push('Poucos detalhes detectados. Verifique o foco e a distância.');
  return {width:source.width,height:source.height,brightness,sharpness,issues};
}
export default function FingerprintPhotoCapture({onAudit}:{onAudit:(event:'camera_opened'|'camera_failed'|'photo_captured'|'photo_discarded'|'photo_failed',diagnostic?:PhotoDiagnostic)=>Promise<void>}){
  const [stream,setStream]=useState<MediaStream|null>(null),[opening,setOpening]=useState(false),[photo,setPhoto]=useState(''),[diagnostic,setDiagnostic]=useState<PhotoDiagnostic|null>(null),[error,setError]=useState(''),[auditing,setAuditing]=useState(false);
  const live=useRef<MediaStream|null>(null),video=useRef<HTMLVideoElement|null>(null),generation=useRef(0),mounted=useRef(true),request=useRef(false),input=useRef<HTMLInputElement|null>(null);
  function stop(){live.current?.getTracks().forEach(track=>track.stop());live.current=null;setStream(null)}
  useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;generation.current++;live.current?.getTracks().forEach(track=>track.stop());live.current=null}},[]);
  useEffect(()=>{if(video.current&&stream){video.current.srcObject=stream;void video.current.play().catch(()=>{if(mounted.current)setError('Toque na prévia para iniciar a câmera.')})}},[stream]);
  async function audit(event:Parameters<typeof onAudit>[0],info?:PhotoDiagnostic){setAuditing(true);try{await onAudit(event,info);return true}catch(e){if(mounted.current)setError('A imagem ficou no aparelho, mas o log não foi registrado: '+(e instanceof Error?e.message:'tente novamente'));return false}finally{if(mounted.current)setAuditing(false)}}
  async function open(){if(request.current)return;request.current=true;setOpening(true);setError('');const id=++generation.current;try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('Câmera indisponível neste navegador. Use a opção Tirar/enviar foto.');stop();const media=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080}},audio:false});if(!mounted.current||id!==generation.current){media.getTracks().forEach(t=>t.stop());return}live.current=media;setStream(media);setPhoto('');setDiagnostic(null);if(!await audit('camera_opened'))stop()}catch(e){if(mounted.current&&id===generation.current){setError(e instanceof Error?e.message:'Não foi possível abrir a câmera.');await audit('camera_failed')}}finally{request.current=false;if(mounted.current)setOpening(false)}}
  async function preview(canvas:HTMLCanvasElement){const info=diagnosePhoto(canvas),url=canvas.toDataURL('image/jpeg',.95);stop();setPhoto(url);setDiagnostic(info);await audit('photo_captured',info)}
  async function capture(){try{if(!video.current?.videoWidth)throw new Error('Aguarde a câmera ficar pronta.');setError('');const canvas=document.createElement('canvas');canvas.width=video.current.videoWidth;canvas.height=video.current.videoHeight;const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Prévia indisponível.');ctx.drawImage(video.current,0,0);await preview(canvas)}catch(e){setError(e instanceof Error?e.message:'Falha na captura.');await audit('photo_failed')}}
  async function upload(file?:File){if(!file)return;setError('');if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10*1024*1024){setError('Use uma foto JPEG, PNG ou WebP de até 10 MB.');await audit('photo_failed');return}const id=++generation.current,url=URL.createObjectURL(file);try{const image=new Image();await new Promise<void>((resolve,reject)=>{image.onload=()=>resolve();image.onerror=()=>reject(new Error('Não foi possível ler a foto.'));image.src=url});if(!mounted.current||id!==generation.current)return;if(image.naturalWidth*image.naturalHeight>24000000)throw new Error('Foto muito grande. Use uma imagem de até 24 megapixels.');const canvas=document.createElement('canvas');canvas.width=image.naturalWidth;canvas.height=image.naturalHeight;const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Prévia indisponível.');ctx.drawImage(image,0,0);await preview(canvas)}catch(e){if(mounted.current){setError(e instanceof Error?e.message:'Falha ao ler imagem.');await audit('photo_failed')}}finally{URL.revokeObjectURL(url);if(input.current)input.current.value=''}}
  async function clear(){generation.current++;stop();setPhoto('');setDiagnostic(null);setError('');await audit('photo_discarded')}
  const button='inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-line bg-white px-4 py-2 text-sm font-bold text-moss-800 disabled:opacity-50';
  return <section aria-label="Captura da digital por foto" className="mt-4 space-y-3"><ol className="list-decimal space-y-1 pl-5 text-sm text-ink"><li>Mostre a parte do dedo que contém a digital, sem encostá-lo na tela.</li><li>Use a câmera traseira, luz uniforme e fundo liso.</li><li>Aproxime até as linhas ficarem nítidas; se perder o foco, afaste um pouco.</li><li>Confira a prévia. Nesta etapa, nenhuma pessoa será identificada.</li></ol><div className="flex flex-wrap gap-2"><button type="button" disabled={opening||auditing} onClick={open} className={button}><Camera aria-hidden="true" className="h-4 w-4"/>{opening?'Abrindo câmera…':'Abrir câmera'}</button><label className={button+' cursor-pointer'}>Tirar/enviar foto<input ref={input} aria-label="Tirar/enviar foto da digital" type="file" accept="image/jpeg,image/png,image/webp" capture="environment" disabled={opening||auditing} onChange={e=>void upload(e.target.files?.[0])} className="sr-only"/></label>{stream&&<button type="button" onClick={()=>{generation.current++;stop()}} className={button}><X aria-hidden="true" className="h-4 w-4"/>Fechar câmera</button>}</div>{stream&&<div className="relative overflow-hidden rounded-xl bg-black"><video ref={video} autoPlay playsInline muted onClick={()=>void video.current?.play()} className="max-h-[420px] w-full object-contain"/><div aria-hidden="true" className="pointer-events-none absolute inset-y-[15%] left-[30%] right-[30%] rounded-[45%] border-2 border-white/80"/><p className="absolute bottom-2 left-2 right-2 rounded-lg bg-black/60 p-2 text-center text-xs text-white">Centralize a ponta do dedo com a digital voltada para a câmera.</p></div>}{stream&&<button type="button" disabled={auditing||opening} onClick={()=>void capture()} className={button+' w-full'}>Fotografar digital</button>}{photo&&<div className="rounded-xl border border-line p-3"><img src={photo} alt="Prévia local da foto da digital" className="mx-auto max-h-[380px] max-w-full rounded-lg object-contain"/>{diagnostic&&<><p className="mt-2 text-xs text-mute">Resolução: {diagnostic.width} × {diagnostic.height} pixels. A verificação fotográfica não confirma qualidade biométrica.</p>{diagnostic.issues.length>0?<ul className="mt-2 list-disc pl-5 text-sm text-ink">{diagnostic.issues.map(issue=><li key={issue}>{issue}</li>)}</ul>:<p className="mt-2 text-sm text-moss-800">Confira se as linhas da digital estão visíveis. Ainda não houve comparação biométrica.</p>}</>}<button type="button" disabled={auditing} onClick={()=>void clear()} className={button+' mt-3'}><RotateCcw aria-hidden="true" className="h-4 w-4"/>Descartar foto</button></div>}{auditing&&<p role="status" className="text-xs text-mute">Registrando tentativa e localização…</p>}{error&&<p role="alert" className="text-sm text-danger-600">{error}</p>}<p className="text-xs text-mute">A foto fica apenas nesta prévia e é descartada ao sair. O servidor recebe o log, a localização e os indicadores fotográficos, sem a imagem.</p></section>;
}
