import {useEffect,useRef,useState} from 'react';
import PaginatedList from './PaginatedList';
import type {HealthEventV1,MyDoctorV1Api,PatientProfile} from '../lib/api-v1';
type CardData={provider:string;planName:string;memberNumber:string;holderName:string;validity:string;notes:string;cardFront:string|null;cardBack:string|null};
const blank=():CardData=>({provider:'',planName:'',memberNumber:'',holderName:'',validity:'',notes:'',cardFront:null,cardBack:null});
const fields=(event:HealthEventV1):CardData=>({...blank(),...event.payload,validity:String(event.payload.validity??'')}) as CardData;
const inactive=(event:HealthEventV1)=>event.status==='cancelled';
const normalized=(text:string)=>text.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('pt-BR');
const input='mt-1 block w-full min-w-0 rounded-lg border border-line bg-white px-3 py-2 text-sm font-normal text-ink';
const button='min-h-11 rounded-lg border border-line px-3 py-2 text-sm font-semibold text-moss-800 disabled:opacity-50';
const primary=button+' bg-pine-900 text-white';
const emptyFilters=()=>({text:'',status:'active',validity:''});
function CardPhoto({src,label}:{src:string;label:string}){
 const dialog=useRef<HTMLDialogElement>(null);
 return <figure className="min-w-0"><button type="button" aria-label={'Ampliar '+label} className="w-full rounded-lg border border-line bg-paper p-2" onClick={()=>dialog.current?.showModal()}><img src={src} alt={label} className="h-40 w-full object-contain sm:h-48"/></button><figcaption className="mt-1 text-center text-xs text-mute">{label} · toque para ampliar</figcaption><dialog ref={dialog} aria-label={'Carteirinha — '+label} className="max-h-[95vh] w-[95vw] max-w-4xl rounded-xl border border-line bg-white p-4 backdrop:bg-black/60" onClick={e=>{if(e.target===e.currentTarget)dialog.current?.close()}}><div className="mb-3 flex items-center justify-between gap-3"><strong>{label}</strong><button type="button" className={button} onClick={()=>dialog.current?.close()}>Fechar imagem</button></div><img src={src} alt={'Imagem ampliada — '+label} className="max-h-[78vh] w-full object-contain"/></dialog></figure>;
}
export default function InsurancePanel({api,profile,events,onRefresh,prepareImage}:{api:MyDoctorV1Api;profile:PatientProfile;events:HealthEventV1[];onRefresh:()=>Promise<void>;prepareImage:(file:File)=>Promise<string>}){
 const [form,setForm]=useState<CardData|null>(null),[editing,setEditing]=useState<HealthEventV1|null>(null),[selected,setSelected]=useState<string|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const [draft,setDraft]=useState(emptyFilters),[filters,setFilters]=useState(emptyFilters);
 const photoVersion=useRef(0);useEffect(()=>()=>{photoVersion.current++},[]);
 const today=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10);
 const items=events.filter(event=>event.patientId===profile.id&&event.type==='insurance').sort((a,b)=>b.occurredAt.localeCompare(a.occurredAt));
 const rows=items.filter(event=>{
  const data=fields(event),off=inactive(event);
  if(filters.status==='active'&&off||filters.status==='inactive'&&!off)return false;
  if(filters.text&&!normalized([data.provider,data.planName,data.memberNumber,data.holderName,data.notes].join(' ')).includes(normalized(filters.text)))return false;
  if(filters.validity==='current'&&(!data.validity||data.validity<today)||filters.validity==='expired'&&(!data.validity||data.validity>=today)||filters.validity==='none'&&data.validity)return false;
  return true;
 });
 const activeFilter=!!filters.text||filters.status!=='active'||!!filters.validity;
 const detail=items.find(event=>event.id===selected);
 const cancel=()=>{photoVersion.current++;setForm(null);setEditing(null)};
 const open=(event?:HealthEventV1)=>{photoVersion.current++;setEditing(event??null);setForm(event?fields(event):blank());setSelected(null);setMessage('')};
 const run=async(work:()=>Promise<void>)=>{if(busy)return;setBusy(true);setMessage('');try{await work()}catch(e){setMessage(e instanceof Error?e.message:'Não foi possível concluir a operação.')}finally{setBusy(false)}};
 const save=()=>run(async()=>{
  if(!form?.provider.trim())throw new Error('Informe o convênio/operadora.');
  const payload={...(editing?.payload??{}),...form,provider:form.provider.trim(),planName:form.planName.trim(),memberNumber:form.memberNumber.trim(),holderName:form.holderName.trim(),validity:form.validity||null,status:'active'};
  const input={type:'insurance',title:'Convênio: '+payload.provider+(payload.planName?' · '+payload.planName:''),occurredAt:editing?.occurredAt??new Date().toISOString(),payload};
  if(editing)await api.updateHealthEvent(profile.id,editing.id,input);else await api.createHealthEvent(profile.id,input);
  await onRefresh();cancel();setMessage('Convênio salvo.');
 });
 const toggle=(event:HealthEventV1)=>run(async()=>{
  if(!window.confirm(inactive(event)?'Reativar este convênio?':'Inativar este convênio? O cadastro e as imagens serão preservados no histórico.'))return;
  if(inactive(event))await api.reactivateHealthEvent(profile.id,event.id);else await api.inactivateHealthEvent(profile.id,event.id,'Convênio inativado pelo usuário.');
  await onRefresh();if(editing?.id===event.id)cancel();setMessage(inactive(event)?'Convênio reativado.':'Convênio inativado e preservado no histórico.');
 });
 const photo=(side:'cardFront'|'cardBack',file?:File)=>{if(!file||!form)return;const version=photoVersion.current;void run(async()=>{const image=await prepareImage(file);if(version===photoVersion.current)setForm(current=>current?{...current,[side]:image}:null)})};
 return <div className="min-w-0 space-y-4">
  <section className="rounded-xl border border-line bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-display text-xl font-bold text-ink">Convênios</h2><p className="text-sm text-mute">{profile.name}</p></div><button type="button" className={primary} disabled={busy} onClick={()=>open()}>+ Incluir convênio</button></div>
   {message&&<p role="status" className="mt-3 rounded-lg bg-paper p-3 text-sm">{message}</p>}
   <details className="group mt-4 rounded-lg border border-line p-3"><summary className="flex cursor-pointer flex-wrap items-center gap-2 text-sm font-bold text-moss-800"><span aria-hidden="true" className="transition-transform group-open:rotate-180">▾</span><span>Filtros de convênios</span>{activeFilter&&<span className="rounded bg-moss-50 px-2 py-1 text-xs">Filtro ativo</span>}<span className="ml-auto text-xs font-normal text-mute">{rows.length} de {items.length} convênios</span></summary><form className="mt-3 grid gap-3 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();setFilters({...draft,text:draft.text.trim()});setSelected(null)}}><label className="text-xs font-bold text-mute sm:col-span-2">Pesquisar operadora, plano, carteirinha ou titular<input className={input} value={draft.text} onChange={e=>setDraft({...draft,text:e.target.value})}/></label><label className="text-xs font-bold text-mute">Status<select aria-label="Status do convênio" className={input} value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}><option value="active">Ativos</option><option value="inactive">Inativos</option><option value="all">Todos</option></select></label><label className="text-xs font-bold text-mute">Validade<select aria-label="Filtrar validade do convênio" className={input} value={draft.validity} onChange={e=>setDraft({...draft,validity:e.target.value})}><option value="">Todas</option><option value="current">Dentro da validade</option><option value="expired">Vencida</option><option value="none">Não informada</option></select></label><div className="flex flex-wrap gap-2 sm:col-span-2"><button className={primary} type="submit">Aplicar filtros</button><button className={button} type="button" onClick={()=>{setDraft(emptyFilters());setFilters(emptyFilters());setSelected(null)}}>Limpar filtros</button></div></form></details>
   {rows.length===0?<p className="mt-4 text-sm text-mute">{items.length?'Nenhum convênio encontrado. Revise os filtros.':'Nenhum convênio cadastrado. Use + Incluir convênio.'}</p>:<div className="mt-4 overflow-x-auto"><PaginatedList items={rows} resetKey={profile.id+JSON.stringify(filters)} label="Convênios">{pageRows=><table className="w-full min-w-[720px] text-left text-sm"><caption className="sr-only">Convênios de {profile.name}</caption><thead className="bg-paper text-xs text-mute"><tr>{['Operadora / plano','Carteirinha / titular','Validade','Status','Ações'].map(label=><th scope="col" key={label} className="px-3 py-2">{label}</th>)}</tr></thead><tbody>{pageRows.map(event=>{const data=fields(event);return <tr key={event.id} data-insurance-id={event.id} className="border-t border-line align-top"><td className="px-3 py-2"><strong>{data.provider||event.title}</strong><p className="text-xs text-mute">{data.planName}</p></td><td className="px-3 py-2">{data.memberNumber||'Não informada'}<p className="text-xs text-mute">{data.holderName}</p></td><td className="px-3 py-2 whitespace-nowrap">{data.validity?data.validity.split('-').reverse().join('/'):'Não informada'}{data.validity&&data.validity<today&&<p className="text-xs text-warn-600">Vencida</p>}</td><td className="px-3 py-2">{inactive(event)?'Inativo':'Ativo'}</td><td className="px-3 py-2"><div className="flex flex-wrap gap-1"><button className={button} type="button" onClick={()=>{cancel();setSelected(event.id)}}>Consultar</button>{!inactive(event)&&<button className={button} type="button" disabled={busy} onClick={()=>open(event)}>Editar</button>}<button className={button} type="button" disabled={busy} onClick={()=>void toggle(event)}>{inactive(event)?'Reativar':'Inativar'}</button></div></td></tr>})}</tbody></table>}</PaginatedList></div>}
  </section>
  {detail&&<section className="rounded-xl border border-line bg-white p-4"><div className="flex items-center justify-between gap-3"><h3 className="text-lg font-bold">{fields(detail).provider||detail.title}</h3><button type="button" className={button} onClick={()=>setSelected(null)}>Fechar consulta</button></div><p className="mt-2 text-sm">{fields(detail).planName} · {fields(detail).holderName}</p><p className="text-sm">Carteirinha: {fields(detail).memberNumber||'Não informada'}</p><p className="text-sm">Validade: {fields(detail).validity?fields(detail).validity.split('-').reverse().join('/'):'Não informada'} · {inactive(detail)?'Inativo':'Ativo'}</p><p className="mt-2 whitespace-pre-wrap text-sm">{fields(detail).notes}</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{fields(detail).cardFront&&<CardPhoto src={fields(detail).cardFront!} label="Frente da carteirinha"/>}{fields(detail).cardBack&&<CardPhoto src={fields(detail).cardBack!} label="Verso da carteirinha"/>}</div>{!fields(detail).cardFront&&!fields(detail).cardBack&&<p className="mt-3 text-sm text-mute">Nenhuma imagem da carteirinha cadastrada.</p>}</section>}
  {form&&<section className="rounded-xl border border-line bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="text-lg font-bold">{editing?'Editar convênio':'Novo convênio'}</h3><button className={button} disabled={busy} type="button" onClick={cancel}>Cancelar sem salvar</button></div><form className="mt-3 grid min-w-0 gap-3 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();void save()}}>
   {([['provider','Convênio / operadora'],['planName','Plano / categoria'],['memberNumber','Número da carteirinha'],['holderName','Nome do titular'],['validity','Validade da carteirinha']] as const).map(([key,label])=><label key={key} className="min-w-0 text-xs font-bold text-mute">{label}<input type={key==='validity'?'date':'text'} className={input} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}
   <div className="grid min-w-0 gap-3 sm:col-span-2 sm:grid-cols-2">{(['cardFront','cardBack'] as const).map(side=><div key={side} className="min-w-0 rounded-lg border border-line p-3"><label className="text-xs font-bold text-mute">Foto da carteirinha — {side==='cardFront'?'frente':'verso'}<input type="file" accept="image/*" capture="environment" disabled={busy} className="mt-2 block w-full min-w-0 text-xs" onChange={e=>photo(side,e.target.files?.[0])}/></label>{form[side]&&<><div className="mt-3"><CardPhoto src={form[side]!} label={side==='cardFront'?'Prévia da frente':'Prévia do verso'}/></div><button type="button" className={button+' mt-2'} disabled={busy} onClick={()=>setForm({...form,[side]:null})}>Remover foto {side==='cardFront'?'da frente':'do verso'}</button></>}</div>)}</div>
   <label className="text-xs font-bold text-mute sm:col-span-2">Observações<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} className={input+' min-h-20'}/></label><div className="flex flex-wrap gap-2 sm:col-span-2"><button type="submit" disabled={busy} className={primary}>{busy?'Salvando...':editing?'Salvar alterações':'Salvar convênio'}</button><button type="button" disabled={busy} className={button} onClick={cancel}>Cancelar</button></div>
  </form></section>}
 </div>;
}
