import { useState } from 'react';
import EncounterFields, { FollowUpFields, localFollowUp, savedFollowUp, type EncounterFieldsValue } from './EncounterFields';
import type { MyDoctorV1Api, ProfessionalConsultationDetailV1, ProfessionalProfileV1 } from '../lib/api-v1';

const TYPES = [['consultation','Consulta'],['exam','Exame'],['hospitalization','Internação'],['procedure','Procedimento'],['therapy','Terapia/Fisioterapia'],['vaccine','Vacina'],['prescription','Receita/Prescrição'],['other','Outro']];
const FIELDS = [['symptoms','Sintomas / Queixa principal'],['diagnosis','Diagnóstico / Causa / Hipótese'],['exams','Exames'],['prescriptions','Receitas / Prescrições'],['notes','Observações']] as const;
const CATEGORIES = [['report','Laudo / Relatório'],['prescription','Receita / Prescrição'],['exam','Exames']] as const;
const input = 'mt-1 block w-full rounded-lg border border-line bg-white px-3 py-2 text-sm font-normal text-ink';
const localDate = (date: Date) => new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16);
export function encounterStatus(status: string) { return status==='draft'?'Rascunho — ainda não enviado':['final','amended'].includes(status)?'Aprovado — somente consulta':status==='cancelled'?'Inativo — somente consulta':status==='rejected_by_patient'?'Recusado pelo paciente':'Aguardando aprovação do paciente'; }
function fieldsFor(record?: ProfessionalConsultationDetailV1 | null) { return { followUp:localFollowUp(record?.payload.followUp),title: record?.title ?? '', type: record?.type ?? 'consultation', occurredAt: localDate(record ? new Date(record.occurredAt) : new Date()), organizationName: record?.organizationNameSnapshot ?? '', homeVisit: record?.payload.homeVisit === true, onlineVisit: record?.payload.onlineVisit === true, ...Object.fromEntries(FIELDS.map(([key])=>[key,String(record?.payload[key] ?? '')])) } as EncounterFieldsValue; }

export default function ProfessionalEncounterEditor({ api, record, accessRequestId, patientName, profile, onSaved, onClose, onBusy, locations }: { api: MyDoctorV1Api; record?: ProfessionalConsultationDetailV1 | null; accessRequestId?: string; patientName: string; profile: ProfessionalProfileV1 | null; onSaved: () => Promise<void>; onClose?: () => void; onBusy: (busy:boolean)=>void; locations?: Array<{id:string;name:string;address?:string}> }) {
  const [saved,setSaved]=useState(record ?? null),[fields,setFields]=useState(()=>fieldsFor(record)),[files,setFiles]=useState<Record<string,File[]>>({report:[],prescription:[],exam:[]}),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  const locked=saved?.status==='final' || saved?.editable===false;
  const dirty=!saved || JSON.stringify(fields)!==JSON.stringify(fieldsFor(saved));
  const hasFiles=Object.values(files).some(list=>list.length);
  const apply=(value:ProfessionalConsultationDetailV1)=>{setSaved(value);setFields(fieldsFor(value));};
  const refreshRecord=async(id:string)=>{const value=await api.getProfessionalConsultation(id);apply(value);return value;};
  const begin=()=>{setBusy(true);onBusy(true);setMessage('');};
  const end=()=>{setBusy(false);onBusy(false);};
  const save=async()=>{
    if(!fields.title.trim())return setMessage('Informe a descrição do atendimento.');
    const date=new Date(fields.occurredAt);if(!fields.occurredAt||Number.isNaN(date.getTime()))return setMessage('Informe uma data e hora válidas.');
    begin();let id=saved?.id;
    try {
      const payload={...fields,followUp:savedFollowUp(fields.followUp),organizationName:fields.onlineVisit||fields.homeVisit?'':fields.organizationName,occurredAt:date.toISOString()};
      const result=id ? await api.updateProfessionalConsultation(id,{...payload,expectedUpdatedAt:saved!.updatedAt}) : await api.createProfessionalConsultation({...payload,accessRequestId:accessRequestId!,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone});
      id=result.id;await refreshRecord(id);
      for(const [category] of CATEGORIES)for(const file of files[category]){await api.uploadHealthEventDocuments(result.patientId,id,category,[file]);setFiles(current=>({...current,[category]:current[category].filter(item=>item!==file)}));}
      await refreshRecord(id);await onSaved();setMessage(result.status==='pending_patient_confirmation'?'Alterações salvas. O atendimento continua aguardando aprovação.':'Atendimento salvo. Você pode revisar e enviar para aprovação.');
    } catch(error) {
      if(id){try{await refreshRecord(id);await onSaved();}catch{ /* preserve the existing form if refresh fails */ }}
      setMessage(error instanceof Error?error.message:'Não foi possível salvar o atendimento.');
    } finally {end();}
  };
  const send=async()=>{if(!saved)return;begin();try{await api.submitProfessionalConsultation(saved.id,saved.updatedAt);await refreshRecord(saved.id);await onSaved();setMessage('Atendimento enviado para aprovação do paciente.')}catch(error){try{await refreshRecord(saved.id)}catch{}setMessage(error instanceof Error?error.message:'Não foi possível enviar.')}finally{end()}};
  const remove=async(documentId:string)=>{if(!saved)return;begin();try{await api.removeProfessionalConsultationDocument(saved.id,documentId);await refreshRecord(saved.id);await onSaved();setMessage('Anexo removido.')}catch(error){try{await refreshRecord(saved.id)}catch{}setMessage(error instanceof Error?error.message:'Não foi possível remover o anexo.')}finally{end()}};
  const registration=profile?.registrations.find(item=>item.status==='active')??profile?.registrations[0];
  return <section className="rounded-xl border border-line bg-white p-4"><div className="mb-4 flex flex-wrap items-center justify-between gap-2"><div><h4 className="font-display text-lg font-bold text-ink">{patientName} · {locked?'Consultar atendimento':saved?'Editar atendimento':'Novo atendimento'}</h4><p className="mt-1 text-xs font-semibold text-moss-700">{saved?encounterStatus(saved.status):'Salve o atendimento antes de enviá-lo ao paciente.'}</p></div>{accessRequestId&&saved&&<button type="button" disabled={busy||dirty||hasFiles} onClick={()=>{setSaved(null);setFields(fieldsFor());setFiles({report:[],prescription:[],exam:[]});setMessage('')}} className="rounded-lg border border-line px-3 py-2 text-xs font-bold disabled:opacity-50">Novo atendimento</button>}{onClose&&<button type="button" disabled={busy} onClick={onClose} className="rounded-lg border border-line px-3 py-2 text-xs font-bold">Fechar</button>}</div>
    {locked ? <div className="space-y-3 text-sm"><strong>{saved?.title}</strong><p className="text-xs text-mute">{saved&&new Date(saved.occurredAt).toLocaleString('pt-BR')} · {TYPES.find(([type])=>type===saved?.type)?.[1]}</p>{saved?.payload.onlineVisit === true && <p className="font-semibold">Atendimento on-line</p>}{saved?.payload.homeVisit === true && <p className="font-semibold">Atendimento domiciliar</p>}<p>{saved?.organizationNameSnapshot}</p>{(saved?.payload.followUp as any)?.enabled&&<p className="rounded-lg bg-paper p-3">Retorno: {new Date((saved!.payload.followUp as any).at).toLocaleString('pt-BR')}</p>}<p className="text-xs text-mute">{saved?.practitionerNameSnapshot} · {String(saved?.payload.specialty ?? 'Especialidade não informada')} · {saved?.councilSnapshot} {saved?.registrationSnapshot}{saved?.registrationRegionSnapshot?`/${saved.registrationRegionSnapshot}`:''}</p>{FIELDS.map(([key,label])=>saved?.payload[key]?<div key={key}><strong className="text-xs text-mute">{label}</strong><p className="whitespace-pre-wrap break-words">{String(saved.payload[key])}</p></div>:null)}</div> : <fieldset disabled={busy} className="grid min-w-0 gap-3 sm:grid-cols-2"><EncounterFields value={fields} onChange={setFields} locations={locations}><div className="rounded-lg border border-line bg-paper p-3 text-sm"><strong>{saved?.practitionerNameSnapshot ?? profile?.name}</strong><p className="text-xs text-mute">{String(saved?.payload.specialty ?? profile?.specialty ?? 'Especialidade não informada')}</p><p className="text-xs text-mute">{saved?.councilSnapshot ?? registration?.council} {saved?.registrationSnapshot ?? registration?.registration}{(saved?.registrationRegionSnapshot ?? registration?.region)?`/${saved?.registrationRegionSnapshot ?? registration?.region}`:''}</p></div></EncounterFields></fieldset>}
    {saved?.documents.length ? <div className="mt-4 space-y-2"><h5 className="text-xs font-bold text-mute">Anexos salvos</h5>{saved.documents.map(doc=><div key={doc.id} className="flex items-center justify-between gap-3 rounded-lg border border-line p-2 text-xs"><button type="button" className="min-w-0 break-words text-left font-semibold text-moss-700 underline" onClick={()=>void api.openHealthEventDocument(saved.patientId,saved.id,doc.id,doc.originalFilename).catch(error=>setMessage(error instanceof Error?error.message:'Não foi possível abrir o anexo.'))}>{doc.originalFilename}</button>{!locked&&<button type="button" disabled={busy||dirty} onClick={()=>void remove(doc.id)}>Remover</button>}</div>)}</div>:null}
    {!locked&&<><div className="mt-4 grid gap-3 sm:grid-cols-3">{CATEGORIES.map(([category,label])=><div key={category} className="rounded-lg border border-line p-3"><label className="text-xs font-bold text-mute">{label}<input disabled={busy} type="file" multiple accept="application/pdf,image/jpeg,image/png,image/webp" className="mt-2 block w-full text-xs" onChange={e=>setFiles(current=>({...current,[category]:[...current[category],...Array.from(e.target.files??[])]}))}/></label>{files[category].map((file,index)=><div key={`${file.name}-${index}`} className="mt-2 flex items-center justify-between gap-2 text-xs"><span className="truncate">{file.name}</span><button type="button" disabled={busy} onClick={()=>setFiles(current=>({...current,[category]:current[category].filter((_,i)=>i!==index)}))}>Remover</button></div>)}</div>)}</div><div className="mt-4"><FollowUpFields value={fields.followUp} occurredAt={fields.occurredAt} onChange={followUp=>setFields({...fields,followUp})} disabled={busy}/></div><div className="mt-4 flex flex-wrap gap-2"><button type="button" disabled={busy} onClick={()=>void save()} className="rounded-xl bg-pine-900 px-4 py-3 text-sm font-bold text-white disabled:opacity-50">{busy?'Processando...':saved?'Salvar alterações':'Salvar atendimento'}</button>{saved&&['draft','rejected_by_patient'].includes(saved.status)&&<button type="button" disabled={busy||dirty||hasFiles||!saved.canSubmit} onClick={()=>void send()} className="rounded-xl border border-moss-500 px-4 py-3 text-sm font-bold text-moss-800 disabled:opacity-50">Enviar para aprovação</button>}</div>{saved&&['draft','rejected_by_patient'].includes(saved.status)&&<p className="mt-2 text-xs text-mute">{!saved.canSubmit?'Solicite uma autorização ativa para enviar ao paciente.':dirty||hasFiles?'Salve o texto e os anexos antes de enviar.':'O envio solicita a aprovação do paciente.'}</p>}</>}
    {message&&<p role="status" className="mt-3 rounded-lg bg-paper p-3 text-sm">{message}</p>}
  </section>;
}



