import PaginatedList from './PaginatedList';
import {useEffect,useRef,useState} from 'react';
import DictationTextarea from './DictationTextarea';
import {ENCOUNTER_TYPES} from './EncounterFields';
import type {MyDoctorV1Api} from '../lib/api-v1';
type Item=Awaited<ReturnType<MyDoctorV1Api['getProfessionalAgenda']>>[number];
const input='mt-1 block w-full min-w-0 rounded-lg border border-line bg-white px-3 py-2 text-sm text-ink';
const local=(value:string)=>{const d=new Date(value);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)};
const labels:Record<string,string>={scheduled:'Programado',completed:'Concluído',cancelled:'Cancelado'};
const months=Array.from({length:12},(_,i)=>new Date(2026,i,1).toLocaleDateString('pt-BR',{month:'long'}));
const emptyForm=()=>({id:'',title:'',at:'',notes:'',alert:true,locationId:'',patientId:'',patientName:'',expectedUpdatedAt:''});
export default function ProfessionalAgenda({api}:{api:MyDoctorV1Api}){
  const [items,setItems]=useState<Item[]>([]),[locations,setLocations]=useState<Awaited<ReturnType<MyDoctorV1Api['listProfessionalLocations']>>>([]);
  const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[show,setShow]=useState(false),[filter,setFilter]=useState('scheduled');
  const [year,setYear]=useState(new Date().getFullYear()),[month,setMonth]=useState(new Date().getMonth()),[day,setDay]=useState('');
  const [form,setForm]=useState(emptyForm),[locationFilter,setLocationFilter]=useState('');
  const dailyRef=useRef<HTMLDivElement>(null),searchVersion=useRef(0);
  const [matches,setMatches]=useState<Awaited<ReturnType<MyDoctorV1Api['searchAgendaPatients']>>['items']>([]),[searching,setSearching]=useState(false),[searchMessage,setSearchMessage]=useState('');
  const resetSearch=()=>{searchVersion.current++;setMatches([]);setSearchMessage('');setSearching(false)};
  const newAppointment=()=>{resetSearch();setForm({...emptyForm(),title:'Consulta',at:day?day+'T09:00':''});setShow(true)};
  const searchPatients=async()=>{const version=++searchVersion.current;setMatches([]);setSearchMessage('');if(form.patientName.trim().length<2&&!/^[1-9][0-9]{0,8}$/.test(form.patientName.trim())){setSearchMessage('Informe o número do prontuário ou pelo menos duas letras do nome.');return}setSearching(true);try{const result=await api.searchAgendaPatients(form.patientName.trim());if(version===searchVersion.current){setMatches(result.items);setSearchMessage(result.total?`${result.total} paciente(s) encontrado(s) para “${form.patientName.trim()}”. ${result.total>20?'Mostrando os primeiros 20; refine o nome para reduzir a lista. ':''}Confira documento e prontuário e clique em Selecionar.`:`Pesquisa concluída para “${form.patientName.trim()}”: nenhum paciente encontrado. Tente outra parte do nome. Também pode salvar apenas o nome digitado.`)}}catch(e){if(version===searchVersion.current)setSearchMessage(e instanceof Error?e.message:'Não foi possível pesquisar.')}finally{if(version===searchVersion.current)setSearching(false)}};
  useEffect(()=>()=>{searchVersion.current++},[]);
  useEffect(()=>{if(day)dailyRef.current?.scrollIntoView?.({behavior:'smooth',block:'start'})},[day]);
  const load=async()=>setItems(await api.getProfessionalAgenda());
  useEffect(()=>{let current=true;Promise.all([api.getProfessionalAgenda(),api.listProfessionalLocations()]).then(([value,places])=>{if(current){setItems(value);setLocations(places)}}).catch(e=>{if(current)setMessage(e.message)});return()=>{current=false}},[api]);
  const run=async(work:()=>Promise<void>)=>{setBusy(true);setMessage('');try{await work();await load()}catch(e){setMessage(e instanceof Error?e.message:'Não foi possível atualizar a agenda.')}finally{setBusy(false)}};
  const save=()=>run(async()=>{if(!form.title.trim()||!form.at)throw new Error('Informe descrição e data/hora.');await api.saveProfessionalAgenda({...form,at:new Date(form.at).toISOString()});const date=new Date(form.at);setYear(date.getFullYear());setMonth(date.getMonth());setDay(local(new Date(form.at).toISOString()).slice(0,10));setShow(false);resetSearch();setMessage('Compromisso salvo na sua agenda.');});
  const changeStatus=(item:Item,status:string)=>run(async()=>{await api.saveProfessionalAgenda({id:item.id,action:'status',status,expectedUpdatedAt:item.updatedAt});setMessage('Situação atualizada.');});
  const prefix=`${year}-${String(month+1).padStart(2,'0')}`;
  const monthly=items.filter(item=>(filter==='all'||item.status===filter)&&(!locationFilter||item.locationId===locationFilter||item.locationName===locations.find(place=>place.id===locationFilter)?.name)&&local(item.at).startsWith(prefix));
  const dailyLocations=day?locations.filter(place=>!locationFilter||place.id===locationFilter).flatMap(place=>(place.availability??[]).filter(slot=>slot.weekday===new Date(day+'T12:00').getDay()).map(slot=>({place,slot}))):[];
  const rows=monthly.filter(item=>!day||local(item.at).startsWith(day)).sort((a,b)=>Date.parse(a.at)-Date.parse(b.at)||a.id.localeCompare(b.id));
  const due=items.filter(item=>item.status==='scheduled'&&item.alert&&Date.parse(item.at)<=Date.now());
  const days=new Date(year,month+1,0).getDate(),padding=new Date(year,month,1).getDay();
  const counts=new Map<string,number>();monthly.forEach(item=>{const key=local(item.at).slice(0,10);counts.set(key,(counts.get(key)??0)+1)});
  const years=[...new Set([...Array.from({length:16},(_,i)=>new Date().getFullYear()-5+i),...items.map(item=>new Date(item.at).getFullYear()),year])].sort((a,b)=>a-b);
  return <section className="min-w-0 space-y-4">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-display text-xl font-bold text-ink">Minha agenda profissional</h2><p className="mt-1 text-sm text-mute">Escolha o mês e clique em um dia para consultar horários, pacientes e locais. A agenda é privada do profissional.</p></div><button type="button" disabled={busy} onClick={newAppointment} className="rounded-xl bg-pine-900 px-4 py-3 text-sm font-bold text-white">+ Novo compromisso</button></div>
    <p className="text-xs text-mute">Alertas aparecem ao abrir o site. Notificações com o aplicativo fechado ainda não estão disponíveis. Retornos são programações e não reservam horário junto ao paciente.</p>
    {due.length>0&&<p role="status" className="rounded-xl border border-moss-500 bg-moss-50 p-3 text-sm font-semibold text-moss-800">Alerta: {due.length} compromisso(s) previsto(s) aguardando conferência.</p>}
    {message&&<p role="status" className="rounded-lg bg-white p-3 text-sm">{message}</p>}
    <div className="grid min-w-0 gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className="min-w-0 text-xs font-bold">Ano<select aria-label="Ano da agenda" value={year} onChange={e=>{setYear(Number(e.target.value));setDay('')}} className={input}>{years.map(value=><option key={value} value={value}>{value}</option>)}</select></label><label className="min-w-0 text-xs font-bold">Mês<select aria-label="Mês da agenda" value={month} onChange={e=>{setMonth(Number(e.target.value));setDay('')}} className={input}>{months.map((name,i)=><option key={i} value={i}>{name}</option>)}</select></label><label className="min-w-0 text-xs font-bold">Situação<select aria-label="Filtrar agenda por situação" value={filter} onChange={e=>{setFilter(e.target.value);setDay('')}} className={input}><option value="all">Todos</option>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="min-w-0 text-xs font-bold">Local<select aria-label="Filtrar agenda por local" value={locationFilter} onChange={e=>setLocationFilter(e.target.value)} className={input}><option value="">Todos os locais</option>{locations.map(place=><option key={place.id} value={place.id}>{place.name}</option>)}</select></label></div>
    <div aria-label="Calendário mensal da agenda" className="rounded-xl border border-line bg-white p-2 sm:p-4"><div className="mb-2 flex flex-wrap items-center justify-between gap-2"><h3 className="font-bold capitalize text-ink">{months[month]} de {year}</h3><span className="text-xs text-mute">{monthly.length} compromisso(s) · clique no dia</span></div><div className="grid grid-cols-7 gap-1">{['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'].map(name=><span key={name} className="py-1 text-center text-xs font-bold text-mute">{name}</span>)}{Array.from({length:padding},(_,i)=><span key={'pad'+i}/>)}{Array.from({length:days},(_,i)=>{const number=i+1,key=prefix+'-'+String(number).padStart(2,'0'),count=counts.get(key)??0;return <button key={key} type="button" aria-pressed={day===key} aria-label={`${number} de ${months[month]} de ${year}, ${count} compromissos`} onClick={()=>{setDay(key);setShow(false);resetSearch()}} className={`flex min-h-14 min-w-0 flex-col items-center justify-center rounded-lg border p-1 text-sm ${day===key?'border-moss-500 bg-moss-700 text-white':count?'border-moss-500 bg-moss-50 font-bold text-moss-800':'border-line text-ink'}`}><span>{number}</span>{count>0&&<span className="text-[10px]">● {count}</span>}</button>})}</div></div>
    <div ref={dailyRef} className="scroll-mt-4 flex flex-wrap items-center justify-between gap-2"><h3 className="font-bold text-ink">{day?`Compromissos de ${new Date(day+'T12:00').toLocaleDateString('pt-BR')}`:'Compromissos do mês'}</h3><div className="flex flex-wrap items-center gap-3">{day&&<button type="button" disabled={busy} onClick={newAppointment} className="rounded-lg bg-pine-900 px-3 py-2 text-xs font-bold text-white">+ Adicionar atendimento neste dia</button>}{day&&<button type="button" onClick={()=>setDay('')} className="text-xs font-bold text-moss-800 underline">Mostrar todo o mês</button>}<button type="button" disabled={busy} onClick={()=>void run(async()=>{})} className="text-xs font-bold text-moss-800 underline">Atualizar agenda</button></div></div>
    {day&&<div className="rounded-xl border border-line bg-white p-3"><h3 className="text-sm font-bold">Horários regulares dos locais neste dia</h3><p className="mt-1 text-xs text-mute">Os períodos mostram sua jornada semanal. Confira os compromissos abaixo antes de escolher o horário.</p>{dailyLocations.length?<div className="mt-2 grid gap-2 sm:grid-cols-2">{dailyLocations.map(({place,slot},i)=><button key={place.id+':'+i} type="button" disabled={busy} onClick={()=>{resetSearch();setForm({...emptyForm(),title:'Consulta',locationId:place.id,at:day+'T'+slot.start});setShow(true)}} className="min-w-0 rounded-lg border border-moss-500 bg-moss-50 p-3 text-left"><strong className="block text-sm">{place.name} · {slot.start} às {slot.end}</strong><span className="mt-1 block break-words text-xs text-mute">{place.address}</span><span className="mt-1 block text-xs font-bold text-moss-800">Adicionar atendimento neste local</span></button>)}</div>:<p className="mt-2 text-xs text-mute">Não há horários semanais cadastrados para este dia nos locais selecionados. Você pode adicionar um compromisso pontual.</p>}</div>}
    {show&&<fieldset disabled={busy} className="grid min-w-0 gap-3 rounded-xl border border-line bg-white p-4 sm:grid-cols-2">
      <div className="min-w-0 sm:col-span-2"><div className="flex flex-wrap items-center gap-3"><span className="text-xs font-bold">Nome do paciente</span><button type="button" disabled={searching} onClick={()=>void searchPatients()} className="rounded-lg border border-moss-500 px-3 py-2 text-xs font-bold text-moss-800">{searching?'Pesquisando...':'Pesquisar paciente'}</button></div><label className="block text-xs font-bold"><span className="sr-only">Nome do paciente</span><DictationTextarea value={form.patientName} rows={1} placeholder="Digite ou dite o nome do paciente" onChange={name=>{resetSearch();setForm({...form,patientName:name.slice(0,150),patientId:''})}} className={input}/></label>{form.patientId&&<p className="mt-1 text-xs font-semibold text-moss-800">Paciente vinculado ao cadastro</p>}<p className="mt-1 text-xs text-mute">Busque pelo número do prontuário ou por parte do nome, sem precisar de acentos. Aceita pequenas diferenças de escrita. Não exige autorização do prontuário. Os documentos são exibidos parcialmente para identificação.</p>{(searching||searchMessage)&&<p role="status" aria-live="polite" className="mt-2 rounded-lg border border-moss-500 bg-moss-50 p-3 text-sm font-semibold text-moss-800">{searching?"Pesquisando pacientes… aguarde.":searchMessage}</p>}{matches.length>0&&<ul className="mt-2 space-y-1">{matches.map(person=><li key={person.id}><button type="button" onClick={()=>{resetSearch();setSearchMessage(`Selecionado: ${person.name} · ${person.documentType||'Documento'}: ${person.documentNumber||'não informado'} · Prontuário: ${person.record||'não informado'}`);setForm({...form,patientId:person.id,patientName:person.name})}} className="w-full rounded-lg border border-line px-3 py-2 text-left text-sm font-semibold text-ink"><span className="block font-bold">{person.name}</span><span className="mt-1 block break-words text-xs font-normal text-mute">{person.documentType||'Documento'}: {person.documentNumber||'Não informado'} · Prontuário: {person.record||'Não informado'}</span><span className="mt-1 block text-xs font-bold text-moss-800">Selecionar paciente</span></button></li>)}</ul>}</div>
      <label className="min-w-0 text-xs font-bold">Descrição<select aria-label="Descrição" value={form.title} onChange={e=>setForm({...form,title:e.target.value})} className={input}>{ENCOUNTER_TYPES.map(([type,label])=><option key={type} value={label}>{label}</option>)}{form.title&&!ENCOUNTER_TYPES.some(([,label])=>label===form.title)&&<option value={form.title}>{form.title} (descrição anterior)</option>}</select></label>
      <label className="min-w-0 text-xs font-bold">Data/Hora do compromisso<input type="datetime-local" value={form.at} onChange={e=>setForm({...form,at:e.target.value})} className={input}/></label>
      <label className="min-w-0 text-xs font-bold sm:col-span-2">Local de atendimento<select aria-label="Local de atendimento do compromisso" value={form.locationId} onChange={e=>setForm({...form,locationId:e.target.value})} className={input}><option value="">Sem local definido</option><option value="online">Atendimento on-line</option><option value="home">Atendimento domiciliar</option>{locations.map(place=><option key={place.id} value={place.id}>{place.name}</option>)}{form.locationId&&!['online','home'].includes(form.locationId)&&!locations.some(place=>place.id===form.locationId)&&<option value={form.locationId}>Local anterior (mantido no compromisso)</option>}</select></label>
      <label className="min-w-0 text-xs font-bold sm:col-span-2">Observações<textarea value={form.notes} maxLength={2000} onChange={e=>setForm({...form,notes:e.target.value})} className={input}/></label>
      <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.alert} onChange={e=>setForm({...form,alert:e.target.checked})} style={{width:16,height:16,flex:'0 0 16px'}}/>Mostrar alerta na data</label>
      <div className="flex gap-2 sm:col-span-2"><button type="button" onClick={()=>void save()} className="rounded-lg bg-pine-900 px-4 py-2 font-bold text-white">Salvar compromisso</button><button type="button" onClick={()=>setShow(false)} className="rounded-lg border border-line px-4 py-2">Cancelar edição</button></div>
    </fieldset>}
    {rows.length===0?<p className="rounded-xl border border-dashed border-line bg-white p-5 text-sm text-mute">Nenhum compromisso neste filtro.</p>:<div className="space-y-2"><PaginatedList items={rows} label="Registros">{pageRows=>(<>{pageRows.map(item=><article key={item.id} className="grid min-w-0 gap-3 rounded-xl border border-line bg-white p-3 sm:grid-cols-[180px_1fr_auto]"><div><time className="text-sm font-bold text-moss-800">{day?new Date(item.at).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'}):new Date(item.at).toLocaleString('pt-BR')}</time><p className="text-xs text-mute">{labels[item.status]} · {item.source==='return'?'Retorno':'Compromisso próprio'}</p></div><div className="min-w-0"><h3 className="break-words font-semibold text-ink">{item.title}</h3>{item.patientName&&<p className="text-sm text-mute">Paciente: {item.patientName}</p>}<p className="mt-1 break-words text-sm font-semibold text-moss-800">{item.locationName||'Local não informado'}</p>{item.locationAddress&&<p className="break-words text-xs text-mute">{item.locationAddress}</p>}{item.notes&&<p className="whitespace-pre-wrap break-words text-xs text-mute">{item.notes}</p>}</div><div className="flex flex-wrap gap-2">{item.source==='manual'&&<button type="button" disabled={busy} onClick={()=>{resetSearch();setForm({patientId:item.patientId??'',patientName:item.patientName??'',id:item.id,title:item.title,at:local(item.at),notes:item.notes,alert:item.alert,locationId:item.locationId??'',expectedUpdatedAt:item.updatedAt});setShow(true)}} className="text-xs font-bold text-moss-800 underline">Editar</button>}<select aria-label={`Situação de ${item.title}`} disabled={busy} value={item.status} onChange={e=>void changeStatus(item,e.target.value)} className="max-w-full rounded-lg border border-line p-2 text-xs">{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div></article>)}</>)}</PaginatedList></div>}
  </section>;
}

