import { useEffect, useState } from 'react';
import type { MyDoctorV1Api, ProfessionalLocationV1 } from '../lib/api-v1';

export default function ProfessionalLocations({ api, locations, onChange, disabled, standalone = false }: { api: MyDoctorV1Api; locations: ProfessionalLocationV1[]; onChange: (items: ProfessionalLocationV1[]) => void; disabled: boolean; standalone?: boolean }) {
  const [editing,setEditing]=useState(''),[name,setName]=useState(''),[address,setAddress]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  const reset=()=>{setEditing('');setName('');setAddress('')};
  const save=async()=>{setBusy(true);setMessage('');try{const input={name:name.trim(),address:address.trim()};const item=editing?await api.updateProfessionalLocation(editing,input):await api.createProfessionalLocation(input);onChange(editing?locations.map(old=>old.id===item.id?item:old):[...locations,item]);reset();setMessage('Local salvo. Ele já está disponível no formulário de atendimento.')}catch(error){setMessage(error instanceof Error?error.message:'Não foi possível salvar o local.')}finally{setBusy(false)}};
  const remove=async(item:ProfessionalLocationV1)=>{if(!window.confirm(`Excluir ${item.name} do seu cadastro? Os atendimentos já gravados manterão o local registrado.`))return;setBusy(true);setMessage('');try{await api.removeProfessionalLocation(item.id);onChange(locations.filter(old=>old.id!==item.id));if(editing===item.id)reset();setMessage('Local excluído do cadastro.')}catch(error){setMessage(error instanceof Error?error.message:'Não foi possível excluir.')}finally{setBusy(false)}};
  const Container=standalone?'section':'details', Heading=standalone?'h2':'summary';
  return <Container className="rounded-2xl border border-line bg-card p-4"><Heading className="cursor-pointer font-display text-lg font-bold text-ink">Meus locais de atendimento <span className="text-xs text-mute">({locations.length})</span></Heading><p className="mt-3 text-xs text-mute">Cadastre seus hospitais, clínicas e consultórios para selecionar durante o atendimento. Este cadastro pertence somente a você.</p><fieldset disabled={busy||disabled} className="mt-3 space-y-3"><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold text-mute">Nome do local<input value={name} maxLength={150} onChange={e=>setName(e.target.value)} className="mt-1 block w-full rounded-lg border border-line bg-white px-3 py-2 text-sm font-normal"/></label><label className="text-xs font-bold text-mute">Endereço (opcional)<input value={address} maxLength={300} onChange={e=>setAddress(e.target.value)} className="mt-1 block w-full rounded-lg border border-line bg-white px-3 py-2 text-sm font-normal"/></label></div><div className="flex gap-2"><button type="button" disabled={name.trim().length<2} onClick={()=>void save()} className="rounded-lg bg-pine-900 px-3 py-2 text-sm font-bold text-white disabled:opacity-50">{busy?'Salvando...':editing?'Salvar alterações do local':'Cadastrar local'}</button>{editing&&<button type="button" onClick={reset}>Cancelar edição</button>}</div>{locations.length>0&&<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-line text-xs text-mute"><th className="py-2 pr-3">Local</th><th className="py-2 pr-3">Endereço</th><th className="py-2">Ações</th></tr></thead><tbody>{locations.map(item=><tr key={item.id} className="border-b border-line"><td className="py-2 pr-3 font-semibold">{item.name}</td><td className="py-2 pr-3">{item.address||'—'}</td><td className="py-2"><div className="flex gap-3"><button type="button" onClick={()=>{setEditing(item.id);setName(item.name);setAddress(item.address);setMessage('')}} className="font-semibold text-moss-700">Editar</button><button type="button" onClick={()=>void remove(item)} className="text-danger-600">Excluir</button></div></td></tr>)}</tbody></table></div>}</fieldset>{message&&<p role="status" className="mt-3 text-sm">{message}</p>}</Container>;
}

export function ProfessionalLocationsPage({api}:{api:MyDoctorV1Api}) {
  const [locations,setLocations]=useState<ProfessionalLocationV1[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
  useEffect(()=>{let active=true;setLoading(true);void api.listProfessionalLocations().then(items=>{if(active)setLocations(items)}).catch(reason=>{if(active)setError(reason instanceof Error?reason.message:'Não foi possível carregar os locais.')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[api]);
  return loading?<p role="status">Carregando seus locais...</p>:error?<p role="alert">{error}</p>:<ProfessionalLocations api={api} locations={locations} onChange={setLocations} disabled={false} standalone/>;
}
