import {useEffect,useRef,useState} from 'react';
import type {MyDoctorV1Api,ProfessionalLocationV1,LocationAddressV1,LocationAvailabilityV1} from '../lib/api-v1';
const days=['Domingo','Segunda-feira','Terça-feira','Quarta-feira','Quinta-feira','Sexta-feira','Sábado'];
const emptyAddress=():LocationAddressV1=>({postalCode:'',street:'',number:'',complement:'',neighborhood:'',city:'',state:'',country:'Brasil'});
const field='mt-1 block w-full min-w-0 rounded-lg border border-line bg-white px-3 py-2 text-sm font-normal text-ink';
export default function ProfessionalLocations({api,locations,onChange,disabled,standalone=false}:{api:MyDoctorV1Api;locations:ProfessionalLocationV1[];onChange:(items:ProfessionalLocationV1[])=>void;disabled:boolean;standalone?:boolean}){
 const [editing,setEditing]=useState(''),[name,setName]=useState(''),[address,setAddress]=useState(emptyAddress),[legacy,setLegacy]=useState(''),[availability,setAvailability]=useState<LocationAvailabilityV1[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[cepBusy,setCepBusy]=useState(false);
 const cepVersion=useRef(0);
 useEffect(()=>()=>{cepVersion.current++},[]);
 const reset=()=>{cepVersion.current++;setCepBusy(false);setEditing('');setName('');setAddress(emptyAddress());setLegacy('');setAvailability([])};
 const save=async()=>{setBusy(true);setMessage('');try{
  const structured=!!(address.street||address.city||address.state||address.postalCode||address.number||address.neighborhood||address.complement);
  if(!structured&&!legacy)throw Error('Preencha o endereço do local.');
  const input={name:name.trim(),address:legacy,fullAddress:structured?address:null,availability};
  const item=editing?await api.updateProfessionalLocation(editing,input):await api.createProfessionalLocation(input);
  onChange(editing?locations.map(old=>old.id===item.id?item:old):[...locations,item]);reset();setMessage('Local e disponibilidade semanal salvos. Já podem ser usados na sua agenda.');
 }catch(e){setMessage(e instanceof Error?e.message:'Não foi possível salvar.')}finally{setBusy(false)}};
 const cep=async()=>{const code=address.postalCode.replace(/\D/g,'');if(code.length!==8){setMessage('Informe os 8 números do CEP.');return}const version=++cepVersion.current;setCepBusy(true);setMessage('');try{const result=await api.lookupAddress(code);if(version!==cepVersion.current)return;if(result.erro||!result.localidade)throw Error('CEP não encontrado. Preencha o endereço manualmente.');setAddress(current=>({...current,street:result.logradouro??'',neighborhood:result.bairro??'',city:result.localidade??'',state:result.uf??''}));setMessage('Endereço preenchido pelo CEP. Complete número e complemento.')}catch(e){if(version===cepVersion.current)setMessage(e instanceof Error?e.message:'Preencha o endereço manualmente.')}finally{if(version===cepVersion.current)setCepBusy(false)}};
 const remove=async(item:ProfessionalLocationV1)=>{if(!window.confirm(`Excluir ${item.name}? Os atendimentos gravados manterão o local registrado.`))return;setBusy(true);setMessage('');try{await api.removeProfessionalLocation(item.id);onChange(locations.filter(old=>old.id!==item.id));if(editing===item.id)reset();setMessage('Local excluído.')}catch(e){setMessage(e instanceof Error?e.message:'Não foi possível excluir.')}finally{setBusy(false)}};
 const edit=(item:ProfessionalLocationV1)=>{reset();setEditing(item.id);setName(item.name);setAddress(item.fullAddress??emptyAddress());setLegacy(item.fullAddress?'':item.address);setAvailability(item.availability??[]);setMessage('')};
 const text=(label:string,key:keyof LocationAddressV1,max=180,span='')=><label className={'min-w-0 text-xs font-bold text-mute '+span}>{label}<input value={key==='postalCode'?address[key].replace(/^(\d{5})(\d)/,'$1-$2'):address[key]} maxLength={max} onChange={e=>{cepVersion.current++;setCepBusy(false);setAddress({...address,[key]:key==='postalCode'?e.target.value.replace(/\D/g,'').slice(0,8):key==='state'?e.target.value.toUpperCase():e.target.value})}} className={field}/></label>;
 const Container=standalone?'section':'details',Heading=standalone?'h2':'summary';
 return <Container className="min-w-0 rounded-2xl border border-line bg-card p-4"><Heading className="font-display text-lg font-bold text-ink">Meus locais de atendimento <span className="text-xs text-mute">({locations.length})</span></Heading><p className="mt-2 text-xs text-mute">Cadastre o endereço e os horários regulares de cada local. A disponibilidade é semanal; feriados, bloqueios e reservas de vagas não são automáticos.</p>
 <fieldset disabled={busy||disabled||cepBusy} className="mt-3 min-w-0 space-y-3">
 <label className="block text-xs font-bold text-mute">Nome do local<input value={name} maxLength={150} onChange={e=>setName(e.target.value)} className={field}/></label>
 {legacy&&<p className="rounded-lg bg-white p-2 text-xs text-mute">Endereço anterior: {legacy}. Ele será mantido enquanto você não preencher os campos abaixo.</p>}
 <div className="grid min-w-0 grid-cols-2 gap-3 sm:grid-cols-6"><div className="col-span-2 flex items-end gap-2">{text('CEP','postalCode',9)}<button type="button" onClick={()=>void cep()} className="shrink-0 rounded-lg border border-line px-3 py-2 text-xs font-bold">Buscar CEP</button></div>{text('Rua / Avenida','street',180,'col-span-2 sm:col-span-3')}{text('Número','number',20)}{text('Complemento','complement',100,'col-span-2 sm:col-span-3')}{text('Bairro','neighborhood',100,'col-span-2 sm:col-span-3')}{text('Cidade','city',100,'col-span-2 sm:col-span-3')}{text('Estado / UF','state',40)}{text('País','country',80,'sm:col-span-2')}</div>
 <div className="rounded-xl border border-line bg-white p-3"><h3 className="text-sm font-bold">Disponibilidade semanal neste local</h3><p className="mt-1 text-xs text-mute">Marque os dias e informe início e fim. Para uma pausa, adicione outro período no mesmo dia.</p><div className="mt-2 space-y-2">{days.map((day,weekday)=>{const slots=availability.filter(slot=>slot.weekday===weekday);return <div key={day} className="flex flex-wrap items-center gap-2 border-b border-line py-2"><label className="flex w-36 items-center gap-2 text-xs font-semibold"><input style={{width:16,height:16}} type="checkbox" checked={slots.length>0} onChange={e=>setAvailability(e.target.checked?[...availability,{weekday,start:'09:00',end:weekday===6?'13:00':'17:00'}]:availability.filter(slot=>slot.weekday!==weekday))}/>{day}</label><div className="min-w-0 space-y-1">{slots.map((slot,index)=><div key={index} className="flex flex-wrap items-center gap-2"><input aria-label={'Início '+day+' '+(index+1)} type="time" value={slot.start} onChange={e=>setAvailability(availability.map(old=>old===slot?{...old,start:e.target.value}:old))} className="rounded-lg border border-line p-2 text-sm"/><span className="text-xs">até</span><input aria-label={'Fim '+day+' '+(index+1)} type="time" value={slot.end} onChange={e=>setAvailability(availability.map(old=>old===slot?{...old,end:e.target.value}:old))} className="rounded-lg border border-line p-2 text-sm"/><button type="button" aria-label={'Remover período '+day+' '+(index+1)} onClick={()=>setAvailability(availability.filter(old=>old!==slot))} className="text-xs text-danger-600">Remover</button></div>)}</div>{slots.length>0&&<button type="button" onClick={()=>setAvailability([...availability,{weekday,start:'18:00',end:'20:00'}])} className="text-xs font-bold text-moss-800">+ Período</button>}</div>})}</div></div>
 <div className="flex gap-2"><button type="button" disabled={name.trim().length<2} onClick={()=>void save()} className="rounded-lg bg-pine-900 px-3 py-2 text-sm font-bold text-white disabled:opacity-50">{busy?'Salvando...':editing?'Salvar alterações do local':'Cadastrar local'}</button>{editing&&<button type="button" onClick={reset}>Cancelar edição</button>}</div>
 {locations.length>0&&<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-line text-xs text-mute"><th className="p-2">Local / Endereço</th><th className="p-2">Disponibilidade semanal</th><th className="p-2">Ações</th></tr></thead><tbody>{locations.map(item=><tr key={item.id} className="border-b border-line"><td className="p-2"><strong>{item.name}</strong><p className="mt-1 text-xs">{item.address||'Não informado'}</p></td><td className="p-2 text-xs">{item.availability?.length?item.availability.map((slot,i)=><p key={i}>{days[slot.weekday]} · {slot.start} às {slot.end}</p>):'Horários não informados'}</td><td className="p-2"><div className="flex gap-3"><button type="button" onClick={()=>edit(item)} className="font-semibold text-moss-700">Editar</button><button type="button" onClick={()=>void remove(item)} className="text-danger-600">Excluir</button></div></td></tr>)}</tbody></table></div>}
 </fieldset>{cepBusy&&<p role="status">Consultando CEP...</p>}{message&&<p role="status" className="mt-3 text-sm">{message}</p>}</Container>;
}

export function ProfessionalLocationsPage({api}:{api:MyDoctorV1Api}) {
  const [locations,setLocations]=useState<ProfessionalLocationV1[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
  useEffect(()=>{let active=true;setLoading(true);void api.listProfessionalLocations().then(items=>{if(active)setLocations(items)}).catch(reason=>{if(active)setError(reason instanceof Error?reason.message:'Não foi possível carregar os locais.')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[api]);
  return loading?<p role="status">Carregando seus locais...</p>:error?<p role="alert">{error}</p>:<ProfessionalLocations api={api} locations={locations} onChange={setLocations} disabled={false} standalone/>;
}
