import {useState,type ReactNode} from 'react';
import {ArrowDown,ArrowUp,ArrowUpDown,ChevronDown,Search} from 'lucide-react';
import PaginatedList from './PaginatedList';
export function QueryFilters({title='Filtros',active,count,total,noun,children}:{title?:string;active:boolean;count:number;total:number;noun:string;children:ReactNode}){
 return <details className="group mt-4 rounded-xl border border-line bg-paper p-3 sm:p-4"><summary className="flex min-h-11 cursor-pointer list-none flex-wrap items-center justify-between gap-2 text-sm font-bold text-moss-800"><span className="flex items-center gap-2"><Search aria-hidden="true" className="h-4 w-4"/>{title}{active&&<span className="rounded-full bg-moss-100 px-2 py-0.5 text-xs">Filtro ativo</span>}</span><span className="ml-auto flex items-center gap-2"><span role="status" className="text-right text-xs font-normal text-mute">{count} de {total} {noun}</span><ChevronDown aria-hidden="true" className="h-4 w-4 transition-transform group-open:rotate-180"/></span></summary>{children}</details>;
}
export type QueryColumn<T>={key:string;label:string;value:(item:T)=>string|number;render?:(item:T)=>ReactNode};
export default function QueryList<T extends {id:string}>({items,columns,label,selected,onSelect,renderDetails,resetKey='',dataAttribute='data-query-id'}:{items:T[];columns:QueryColumn<T>[];label:string;selected:string|null;onSelect:(id:string|null)=>void;renderDetails:(item:T)=>ReactNode;resetKey?:string;dataAttribute?:string}){
 const [sort,setSort]=useState({key:columns[0].key,direction:'asc' as 'asc'|'desc'});
 const column=columns.find(item=>item.key===sort.key)??columns[0];
 const collator=new Intl.Collator('pt-BR',{sensitivity:'base',numeric:true});
 const sorted=[...items].sort((a,b)=>{const left=column.value(a),right=column.value(b);return (typeof left==='number'&&typeof right==='number'?left-right:collator.compare(String(left),String(right)))*(sort.direction==='asc'?1:-1)||a.id.localeCompare(b.id)});
 const change=(key:string)=>setSort(current=>({key,direction:current.key===key&&current.direction==='asc'?'desc':'asc'}));
 const toggle=(item:T)=>onSelect(selected===item.id?null:item.id);
 return <div className="min-w-0"><div className="mb-3 flex flex-wrap items-end gap-2 md:hidden"><label className="min-w-0 flex-1 text-xs font-bold text-mute">Ordenar por<select aria-label={'Ordenar '+label} className="mt-1 block min-h-11 w-full rounded-lg border border-line bg-white px-3 py-2 text-sm" value={sort.key} onChange={e=>setSort({key:e.target.value,direction:'asc'})}>{columns.map(item=><option key={item.key} value={item.key}>{item.label}</option>)}</select></label><button type="button" onClick={()=>change(sort.key)} className="min-h-11 rounded-lg border border-line px-3 py-2 text-xs font-semibold">{sort.direction==='asc'?'Crescente':'Decrescente'}</button></div><div className="overflow-x-auto"><PaginatedList items={sorted} label={label} resetKey={resetKey+JSON.stringify(sort)}>{pageRows=><table className="w-full min-w-[640px] text-left text-sm"><caption className="sr-only">{label}: clique em um registro para consultar os detalhes.</caption><thead className="bg-paper text-xs font-bold text-mute"><tr>{columns.map(item=>{const Icon=item.key===sort.key?(sort.direction==='asc'?ArrowUp:ArrowDown):ArrowUpDown;return <th key={item.key} scope="col" aria-sort={item.key===sort.key?(sort.direction==='asc'?'ascending':'descending'):'none'} className="px-3 py-2"><button type="button" aria-label={'Ordenar por '+item.label} onClick={()=>change(item.key)} className="flex min-h-10 items-center gap-2 text-left hover:text-moss-700">{item.label}<Icon aria-hidden="true" className="h-3.5 w-3.5 shrink-0"/></button></th>})}</tr></thead><tbody>{pageRows.map(item=><QueryRows key={item.id} item={item} columns={columns} open={selected===item.id} toggle={()=>toggle(item)} dataAttribute={dataAttribute} renderDetails={renderDetails}/>)}</tbody></table>}</PaginatedList></div></div>;
}
function QueryRows<T extends {id:string}>({item,columns,open,toggle,dataAttribute,renderDetails}:{item:T;columns:QueryColumn<T>[];open:boolean;toggle:()=>void;dataAttribute:string;renderDetails:(item:T)=>ReactNode}){
 return <><tr {...{[dataAttribute]:item.id}} tabIndex={0} aria-expanded={open} onClick={toggle} onKeyDown={e=>{if(e.target===e.currentTarget&&(e.key==='Enter'||e.key===' ')){e.preventDefault();toggle()}}} className="cursor-pointer border-t border-line align-top hover:bg-moss-50 focus-visible:outline focus-visible:outline-2 focus-visible:outline-moss-500">{columns.map((column,index)=><td key={column.key} className="px-3 py-3">{index===0?<button type="button" aria-expanded={open} className="flex items-center gap-2 text-left font-semibold text-moss-800"><ChevronDown aria-hidden="true" className={'h-4 w-4 shrink-0 transition-transform '+(open?'rotate-180':'')}/>{column.render?.(item)??String(column.value(item))}</button>:column.render?.(item)??String(column.value(item))}</td>)}</tr>{open&&<tr><td colSpan={columns.length} className="border-t border-line bg-paper/40 p-3 sm:p-4">{renderDetails(item)}</td></tr>}</>;
}
