import {randomUUID} from 'node:crypto';
import {Router,type Request,type Response,type NextFunction} from 'express';
import jwt from 'jsonwebtoken';
import prisma from './db.js';
import {administrator,validatedUpload,invalidate} from './professional-admin.js';
import {isUnder18} from './identity-policy.js';
import {managedPatientWhere,managesPatient} from './patient-permissions.js';
import {PersonError,identityInput,identityKeys,personData,claimPerson,findPeople} from './person-identity.js';
const router=Router(),secret=process.env.JWT_SECRET??'dev-only-mydoctor-jwt-secret-change-me';
interface AuthRequest extends Request{userId?:string;admin?:boolean}
function auth(req:AuthRequest,res:Response,next:NextFunction){try{req.userId=(jwt.verify((req.headers.authorization??'').replace(/^Bearer /,''),secret) as {uid:string}).uid;next()}catch{res.status(401).json({error:'Entre novamente.'})}}
async function admin(req:AuthRequest,res:Response,next:NextFunction){try{const result=await administrator(req);if(!result.authorized)return res.status(403).json({error:'Acesso restrito à administração.'});req.userId=result.user.id;req.admin=true;next()}catch{res.status(401).json({error:'Entre novamente.'})}}
const fail=(res:Response,error:unknown)=>res.status(error instanceof PersonError?error.status:503).json({error:error instanceof PersonError?error.message:'Não foi possível concluir. Atualize a consulta e tente novamente.'});
const relations=new Set(['child','parent','guardian','dependent','other']);
const pending=['pending','documents_pending'];
function ticket(token:unknown,uid:string,purpose:string){try{const data=jwt.verify(String(token??''),secret) as any;if(data.uid!==uid||data.purpose!==purpose)throw Error();return data}catch{throw new PersonError(400,'Faça a pesquisa novamente antes de continuar.')}}
const tickets=(data:object)=>jwt.sign(data,secret,{expiresIn:'10m'});
const mask=(value:string)=>value?'•••••••'+value.slice(-4):'Não informado';
const searches=new Map<string,{at:number;count:number}>();
router.post('/people/search',auth,async(req:AuthRequest,res)=>{try{
 if(searches.size>10000){for(const [id,x]of searches)if(Date.now()-x.at>60000)searches.delete(id)}
 const now=Date.now(),old=searches.get(req.userId!);const rate=old&&now-old.at<60000?old:{at:now,count:0};if(++rate.count>20)throw new PersonError(429,'Aguarde um minuto antes de pesquisar novamente.');searches.set(req.userId!,rate);
 const input=identityInput(req.body);const rows=await findPeople(prisma,input,true);
 const keys=identityKeys(input);res.setHeader('Cache-Control','private, no-store');res.json({items:rows.slice(0,20).map(p=>({id:p.id,name:p.name,record:p.record,document:mask(p.cpf),hasTutor:!!p.tutorUserId,archived:!!p.archived,token:tickets({uid:req.userId,purpose:'tutor-candidate',patientId:p.id})})),more:rows.length>20,creationToken:rows.length?null:tickets({uid:req.userId,purpose:'new-person',keys})});
 }catch(e){fail(res,e)}});
export async function createDependent(userId:string,body:any){
 const input=personData(body),proof=ticket(body.creationToken,userId,'new-person');
 const keys=identityKeys(input);if(!proof.keys?.length||!proof.keys.every((key:string)=>keys.includes(key)))throw new PersonError(400,'Os dados de identificação mudaram. Pesquise novamente.');
 const relationship=String(body.relationship??'dependent');if(!relations.has(relationship))throw new PersonError(400,'Selecione a relação com o responsável.');
 return prisma.$transaction(async tx=>{
 const id=randomUUID();const patient=await tx.patient.create({data:{id,record:'PR-'+id.slice(0,8).toUpperCase(),name:input.name,ownerUserId:userId,tutorUserId:userId,tutorManaged:true,data:{...input,relationshipToOwner:relationship,relationshipToTutor:relationship,createdByUserId:userId}}});
 await claimPerson(tx,id,input);await tx.tutorHistory.create({data:{patientId:id,actorUserId:userId,newTutorId:userId,action:'created_with_tutor'}});return {id:patient.id,record:patient.record,name:patient.name,relationship,accessLevel:'tutor',source:'owned',isTutor:true};
 },{timeout:20000});
}
router.get('/people/:id',auth,async(req:AuthRequest,res)=>{try{const p=await prisma.patient.findUnique({where:{id:req.params.id}});if(!p||!managesPatient(p,req.userId!))throw new PersonError(403,'Sem acesso ao cadastro desta pessoa.');let data:any=p.data;if(data.relationshipToOwner==='self'){const u=await prisma.user.findUnique({where:{id:p.ownerUserId},select:{accountData:true}});data={...data,...((u?.accountData??{}) as object)}}
 res.setHeader('Cache-Control','private, no-store');res.json({...Object.fromEntries(['cpf','rg','rgUf','birthDate','motherName','sex','phone','postalCode','street','number','complement','neighborhood','city','state','country','avatarDataUrl'].map(k=>[k,String(data[k]??'')])),name:p.name,id:p.id,canEdit:data.relationshipToOwner!=='self'||p.tutorUserId===req.userId,isTutor:p.tutorUserId===req.userId,hasTutor:!!p.tutorUserId});}catch(e){fail(res,e)}});
router.put('/people/:id',auth,async(req:AuthRequest,res)=>{try{const input=personData(req.body);const result=await prisma.$transaction(async tx=>{await tx.$queryRaw`SELECT id FROM "Patient" WHERE id=${req.params.id} FOR UPDATE`;const p=await tx.patient.findUnique({where:{id:req.params.id}});if(!p||!managesPatient(p,req.userId!))throw new PersonError(403,'Sem acesso para editar.');if((p.data as any)?.relationshipToOwner==='self'&&p.tutorUserId!==req.userId)throw new PersonError(403,'Atualize seu próprio cadastro em Meu cadastro.');const doc=(p.data as any).relationshipToOwner==='self'?await tx.userIdentityDocument.findUnique({where:{userId:p.ownerUserId},select:{kind:true}}):await tx.patientIdentityDocument.findUnique({where:{patientId:p.id},select:{kind:true}});if(doc?.kind==='Certidão de nascimento'&&!isUnder18(input.birthDate))throw new PersonError(400,'Certidão de nascimento é permitida somente para menores de 18 anos.');await claimPerson(tx,p.id,input);if((p.data as any).relationshipToOwner==='self'){const u=await tx.user.findUniqueOrThrow({where:{id:p.ownerUserId},select:{accountData:true}});await tx.user.update({where:{id:p.ownerUserId},data:{name:input.name,accountData:{...(u.accountData as any),...input}}})}return tx.patient.update({where:{id:p.id},data:{name:input.name,data:(p.data as any).relationshipToOwner==='self'?{...(p.data as any),name:input.name,birthDate:input.birthDate,sex:input.sex,city:input.city,state:input.state}:{...(p.data as any),...input}}})});res.json({id:result.id,name:result.name})}catch(e){fail(res,e)}});
const docSelect={id:true,kind:true,filename:true,mimeType:true,sizeBytes:true,createdAt:true} as const;
router.get('/people/:id/document',auth,async(req:AuthRequest,res)=>{try{const p=await prisma.patient.findUnique({where:{id:req.params.id}});if(!p||!managesPatient(p,req.userId!))throw new PersonError(403,'Sem acesso ao documento.');res.json((p.data as any).relationshipToOwner==='self'?await prisma.userIdentityDocument.findUnique({where:{userId:p.ownerUserId},select:docSelect}):await prisma.patientIdentityDocument.findUnique({where:{patientId:p.id},select:docSelect}))}catch(e){fail(res,e)}});
router.post('/people/:id/document',auth,async(req:AuthRequest,res)=>{try{const file=validatedUpload(req.body),kind=String(req.body.kind??'');if(!file||!['CNH','RG','Passaporte','Certidão de nascimento'].includes(kind))throw new PersonError(400,'Envie um documento PDF ou imagem de até 3 MB.');const result=await prisma.$transaction(async tx=>{await tx.$queryRaw`SELECT id FROM "Patient" WHERE id=${req.params.id} FOR UPDATE`;const p=await tx.patient.findUnique({where:{id:req.params.id}});if(!p||!managesPatient(p,req.userId!))throw new PersonError(403,'Sem acesso ao documento.');if((p.data as any)?.relationshipToOwner==='self'&&p.tutorUserId!==req.userId)throw new PersonError(403,'Envie seu documento em Meu cadastro.');if(kind==='Certidão de nascimento'&&!isUnder18((p.data as any).birthDate))throw new PersonError(400,'Certidão de nascimento é permitida somente para menores de 18 anos.');if((p.data as any).relationshipToOwner==='self'){const prof=await tx.practitioner.findUnique({where:{userId:p.ownerUserId}});if(prof)await invalidate(tx,prof);return tx.userIdentityDocument.upsert({where:{userId:p.ownerUserId},update:{kind,...file},create:{userId:p.ownerUserId,kind,...file},select:docSelect})}return tx.patientIdentityDocument.upsert({where:{patientId:p.id},update:{kind,...file},create:{patientId:p.id,kind,...file},select:docSelect})});res.json(result)}catch(e){fail(res,e)}});
router.get('/people/:id/document/download',auth,async(req:AuthRequest,res)=>{try{const p=await prisma.patient.findUnique({where:{id:req.params.id}});if(!p||!managesPatient(p,req.userId!))throw new PersonError(403,'Sem acesso ao documento.');const d=(p.data as any).relationshipToOwner==='self'?await prisma.userIdentityDocument.findUnique({where:{userId:p.ownerUserId}}):await prisma.patientIdentityDocument.findUnique({where:{patientId:p.id}});if(!d)throw new PersonError(404,'Documento não encontrado.');sendDocument(res,d)}catch(e){fail(res,e)}});
function sendDocument(res:Response,d:any){res.setHeader('Cache-Control','private, no-store');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Content-Disposition',`attachment; filename*=UTF-8''${encodeURIComponent(d.filename)}`);res.type(d.mimeType).send(Buffer.from(d.content))}
router.post('/tutorship/requests',auth,async(req:AuthRequest,res)=>{try{
 const proof=ticket(req.body.token,req.userId!,'tutor-candidate'),kind=req.body.kind==='administrative'?'administrative':'ordinary',reason=String(req.body.reason??'').trim(),relationship=String(req.body.relationship??'dependent');
 if(!relations.has(relationship)||reason.length>2000)throw new PersonError(400,'Confira a relação e o motivo.');if(kind==='administrative'&&reason.length<10)throw new PersonError(400,'Explique o motivo da solicitação administrativa.');
 const result=await prisma.$transaction(async tx=>{await tx.$queryRaw`SELECT id FROM "Patient" WHERE id=${proof.patientId} FOR UPDATE`;const p=await tx.patient.findUnique({where:{id:proof.patientId}});if(!p||p.archived)throw new PersonError(404,'Cadastro indisponível. Solicite auxílio administrativo.');if(p.tutorUserId===req.userId||((p.data as any).relationshipToOwner==='self'&&p.ownerUserId===req.userId))throw new PersonError(409,'Este perfil já está sob seu acesso.');if(kind==='ordinary'&&!p.tutorUserId&&(p.data as any).relationshipToOwner!=='self')throw new PersonError(400,'Esta pessoa não tem login próprio nem tutor ativo. Solicite análise administrativa com documentos.');
 const duplicate=await tx.tutorRequest.findFirst({where:{patientId:p.id,requesterUserId:req.userId!,status:{in:pending}}});if(duplicate)throw new PersonError(409,'Você já possui uma solicitação em andamento. Consulte-a antes de solicitar novamente.');
 return tx.tutorRequest.create({data:{patientId:p.id,requesterUserId:req.userId!,expectedTutorId:p.tutorUserId,kind,relationship,reason,status:kind==='administrative'?'documents_pending':'pending'}})});res.status(201).json({id:result.id,status:result.status})
 }catch(e){fail(res,e)}});
async function requestRows(userId:string,isAdmin=false){
 const managed=await prisma.patient.findMany({where:managedPatientWhere(userId),select:{id:true}});
 return prisma.tutorRequest.findMany({where:isAdmin?{kind:'administrative'}:{OR:[{requesterUserId:userId},{patientId:{in:managed.map(p=>p.id)}}]},include:{patient:{select:{name:true,record:true,tutorUserId:true,data:true,ownerUserId:true,tutorManaged:true}},documents:{select:docSelect}},orderBy:{createdAt:'desc'},take:500});
}
async function listRequests(req:AuthRequest,res:Response){try{const rows=await requestRows(req.userId!,req.admin);const ids=[...new Set(rows.map(r=>r.requesterUserId))];const users=await prisma.user.findMany({where:{id:{in:ids}},select:{id:true,name:true}});res.setHeader('Cache-Control','private, no-store');res.json(rows.map(({patient,...r})=>({...r,documents:req.admin||r.requesterUserId===req.userId?r.documents:[],patientName:patient.name,record:patient.record,requesterName:users.find(u=>u.id===r.requesterUserId)?.name??'Usuário',canDecide:req.admin?r.status==='pending':r.kind==='ordinary'&&r.status==='pending'&&(patient.tutorUserId?patient.tutorUserId===req.userId:(patient.data as any).relationshipToOwner==='self'&&patient.ownerUserId===req.userId),mine:r.requesterUserId===req.userId})))}catch(e){fail(res,e)}}
router.get('/tutorship/requests',auth,listRequests);router.get('/admin/tutorship/requests',admin,listRequests);
router.post('/tutorship/requests/:id/documents',auth,async(req:AuthRequest,res)=>{try{const file=validatedUpload(req.body),kind=String(req.body.kind??'');if(!file||!['Identificação do solicitante','Comprovação de responsabilidade','Certidão de óbito','Outro comprovante'].includes(kind))throw new PersonError(400,'Envie um PDF ou imagem de até 3 MB e selecione o tipo.');const result=await prisma.$transaction(async tx=>{await tx.$queryRaw`SELECT id FROM "TutorRequest" WHERE id=${req.params.id} FOR UPDATE`;const r=await tx.tutorRequest.findUnique({where:{id:req.params.id}});if(!r||r.requesterUserId!==req.userId||r.kind!=='administrative'||r.status!=='documents_pending')throw new PersonError(403,'Documentos podem ser enviados somente pelo solicitante quando a documentação está pendente.');if(await tx.tutorDocument.count({where:{requestId:r.id}})>=10)throw new PersonError(400,'Limite de 10 documentos por solicitação.');return tx.tutorDocument.create({data:{requestId:r.id,kind,...file},select:docSelect})});res.status(201).json(result)}catch(e){fail(res,e)}});
router.post('/tutorship/requests/:id/submit',auth,async(req:AuthRequest,res)=>{try{await prisma.$transaction(async tx=>{await tx.$queryRaw`SELECT id FROM "TutorRequest" WHERE id=${req.params.id} FOR UPDATE`;const r=await tx.tutorRequest.findUnique({where:{id:req.params.id},include:{documents:{select:{kind:true}}}});if(!r||r.requesterUserId!==req.userId||r.kind!=='administrative'||r.status!=='documents_pending')throw new PersonError(409,'Atualize a solicitação.');if(!['Identificação do solicitante','Comprovação de responsabilidade'].every(kind=>r.documents.some(d=>d.kind===kind)))throw new PersonError(400,'Anexe identificação do solicitante e comprovação de responsabilidade. Em caso de falecimento, anexe também a certidão de óbito.');await tx.tutorRequest.update({where:{id:r.id},data:{status:'pending'}})});res.json({status:'pending'})}catch(e){fail(res,e)}});
router.get('/tutorship/documents/:id',auth,async(req:AuthRequest,res)=>{try{const d=await prisma.tutorDocument.findUnique({where:{id:req.params.id},include:{request:true}});if(!d||d.request.requesterUserId!==req.userId)throw new PersonError(403,'Sem acesso ao documento.');sendDocument(res,d)}catch(e){fail(res,e)}});
router.get('/admin/tutorship/documents/:id',admin,async(req:AuthRequest,res)=>{try{const d=await prisma.tutorDocument.findUnique({where:{id:req.params.id},include:{request:true}});if(!d||d.request.kind!=='administrative')throw new PersonError(404,'Documento não encontrado.');sendDocument(res,d)}catch(e){fail(res,e)}});
async function changeTutor(tx:any,p:any,newTutor:string|null,actor:string,action:string,requestId?:string,relationship?:string){
 const oldTutor=p.tutorUserId;await tx.patient.update({where:{id:p.id},data:{tutorManaged:true,tutorUserId:newTutor,...(relationship?{data:{...p.data,relationshipToTutor:relationship}}:{})}});
 if(oldTutor&&oldTutor!==newTutor){await tx.accessGrant.updateMany({where:{patientId:p.id,accountId:oldTutor,practitionerId:null,revokedAt:null},data:{revokedAt:new Date()}});const schedules=await tx.medicationSchedule.findMany({where:{patientId:p.id,active:true},select:{id:true,recipientIds:true}});for(const s of schedules)if(Array.isArray(s.recipientIds)&&s.recipientIds.includes(oldTutor))await tx.medicationSchedule.update({where:{id:s.id},data:{recipientIds:s.recipientIds.filter((id:any)=>id!==oldTutor)}})}
 await tx.tutorHistory.create({data:{patientId:p.id,actorUserId:actor,oldTutorId:oldTutor,newTutorId:newTutor,action,requestId}});
 await tx.tutorRequest.updateMany({where:{patientId:p.id,status:{in:pending},...(requestId?{id:{not:requestId}}:{})},data:{status:'cancelled',note:'Vínculo alterado. Pesquise novamente antes de solicitar.',decidedAt:new Date()}});
}
async function decide(req:AuthRequest,res:Response){try{const decision=String(req.body.decision??''),note=String(req.body.note??'').trim();if(!['approve','reject','documents_pending'].includes(decision)||note.length>2000)throw new PersonError(400,'Decisão inválida.');if(decision!=='approve'&&note.length<3)throw new PersonError(400,'Informe o motivo da decisão.');
 await prisma.$transaction(async tx=>{const initial=await tx.tutorRequest.findUnique({where:{id:req.params.id},select:{patientId:true}});if(!initial)throw new PersonError(404,'Solicitação não encontrada.');await tx.$queryRaw`SELECT id FROM "Patient" WHERE id=${initial.patientId} FOR UPDATE`;await tx.$queryRaw`SELECT id FROM "TutorRequest" WHERE id=${req.params.id} FOR UPDATE`;const r=await tx.tutorRequest.findUnique({where:{id:req.params.id},include:{patient:true,documents:{select:{kind:true}}}});if(!r||r.status!=='pending')throw new PersonError(409,'Esta solicitação já foi decidida ou ainda não foi enviada.');const p=r.patient;if(req.admin){if(r.kind!=='administrative')throw new PersonError(403,'Use o fluxo de autorização do responsável.')}else if(r.kind!=='ordinary'||(p.tutorUserId?p.tutorUserId!==req.userId:(p.data as any).relationshipToOwner!=='self'||p.ownerUserId!==req.userId))throw new PersonError(403,'Somente o responsável atual pode decidir.');if(req.userId===r.requesterUserId)throw new PersonError(403,'Você não pode aprovar sua própria solicitação.');if(decision==='documents_pending'&&!req.admin)throw new PersonError(400,'Decisão inválida.');if(p.tutorUserId!==r.expectedTutorId)throw new PersonError(409,'O responsável mudou. Solicite novamente.');
 if(decision==='approve'){if(req.admin&&req.body.checkedDocuments!==true)throw new PersonError(400,'Confirme a conferência dos documentos.');if(req.admin&&!['Identificação do solicitante','Comprovação de responsabilidade'].every(kind=>r.documents.some(d=>d.kind===kind)))throw new PersonError(400,'Documentação obrigatória não encontrada.');await changeTutor(tx,p,r.requesterUserId,req.userId!,'transferred',r.id,r.relationship)}
 await tx.tutorRequest.update({where:{id:r.id},data:{status:decision==='approve'?'approved':decision==='reject'?'rejected':'documents_pending',note,decidedAt:decision==='documents_pending'?null:new Date(),decidedByUserId:req.userId!}})
 },{timeout:20000});res.json({status:decision==='approve'?'approved':decision==='reject'?'rejected':'documents_pending'})}catch(e){fail(res,e)}}
router.post('/tutorship/requests/:id/decision',auth,decide);router.post('/admin/tutorship/requests/:id/decision',admin,decide);
router.post('/tutorship/requests/:id/cancel',auth,async(req:AuthRequest,res)=>{try{const result=await prisma.tutorRequest.updateMany({where:{id:req.params.id,requesterUserId:req.userId!,status:{in:pending}},data:{status:'cancelled',decidedAt:new Date()}});if(!result.count)throw new PersonError(409,'A solicitação já foi decidida.');res.json({status:'cancelled'})}catch(e){fail(res,e)}});
router.post('/people/:id/end-tutorship',auth,async(req:AuthRequest,res)=>{try{if(req.body.confirm!==true)throw new PersonError(400,'Confirme o encerramento da tutoria.');await prisma.$transaction(async tx=>{await tx.$queryRaw`SELECT id FROM "Patient" WHERE id=${req.params.id} FOR UPDATE`;const p=await tx.patient.findUnique({where:{id:req.params.id}});if(!p||!p.tutorUserId||!managesPatient(p,req.userId!))throw new PersonError(403,'Sem permissão para encerrar esta tutoria.');await changeTutor(tx,p,null,req.userId!,'ended')});res.json({ok:true})}catch(e){fail(res,e)}});
router.get('/people/:id/tutorship-history',auth,async(req:AuthRequest,res)=>{try{const p=await prisma.patient.findUnique({where:{id:req.params.id}});if(!p||!managesPatient(p,req.userId!))throw new PersonError(403,'Sem acesso ao histórico.');const rows=await prisma.tutorHistory.findMany({where:{patientId:p.id},orderBy:{at:'desc'},take:500});const ids=[...new Set(rows.flatMap(r=>[r.actorUserId,r.oldTutorId,r.newTutorId].filter((x):x is string=>!!x)))];const users=await prisma.user.findMany({where:{id:{in:ids}},select:{id:true,name:true}});res.json(rows.map(r=>({...r,actorName:users.find(u=>u.id===r.actorUserId)?.name??'Usuário',oldTutorName:users.find(u=>u.id===r.oldTutorId)?.name??'',newTutorName:users.find(u=>u.id===r.newTutorId)?.name??''})))}catch(e){fail(res,e)}});
export default router;
