import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import fs from 'node:fs/promises';
import { build } from 'esbuild';
const require = createRequire(import.meta.url);
const { JSDOM } = require('jsdom');
const { act } = require('react');
const { Simulate } = require('react-dom/test-utils');
const { createRoot } = require('react-dom/client');
const dom = new JSDOM('<div id="root"></div>', { url: 'https://mydoctor.test/' });
for (const key of ['window', 'document', 'navigator', 'MutationObserver', 'HTMLElement', 'HTMLInputElement', 'HTMLTextAreaElement', 'Event', 'CustomEvent']) Object.defineProperty(globalThis, key, { value: dom.window[key], configurable: true });
globalThis.IS_REACT_ACT_ENVIRONMENT = true;
window.sessionStorage.setItem('mydoctor.v1.sessionToken', 'test-session');
window.localStorage.setItem('mydoctor.v1.activeProfileId', 'marco-clinical-patient');
const event = (id, patientId, type, title, status = 'final') => ({ id, patientId, type, title, status, occurredAt: new Date().toISOString(), createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), payload: {} });
const healthEvents = [event('own', 'p1', 'consultation', 'Atendimento próprio'), event('foreign', 'marco-clinical-patient', 'consultation', 'Registro de outra conta'), event('family', 'p1', 'family_history', 'family_history'), event('diary', 'p1', 'wellbeing_diary', 'wellbeing_diary'), event('pending', 'p1', 'consultation', 'Atendimento pendente', 'pending_patient_confirmation')];
healthEvents.push({...event('old-record','p1','consultation','Consulta antiga'),occurredAt:'2025-12-09T15:00:00Z',practitionerNameSnapshot:'Dra. Ana',payload:{specialty:'Dermatologia',notes:'Pele sensível'}},{...event('recent-record','p1','exam','Consulta recente'),occurredAt:'2025-12-10T15:00:00Z',practitionerNameSnapshot:'Dr. Bruno',payload:{specialty:'Cardiologia',notes:'Enxaqueca e revisão'}});
let account = { id: 'u1', name: 'Pessoa teste', email: 'teste@mydoctor.test', phone: '', birthDate: '1980-01-01', sex: '', city: '', state: '', completed: true, isHealthProfessional: true, postalCode: '', street: '', neighborhood: '', country: 'Brasil', number: '42', complement: 'Casa' };
let requests = [];
let pendingConsultations = [{ id: 'confirmed-consultation', patientId: 'p1', patientName: 'Pessoa teste', title: 'Consulta do Dr. Lucas', practitionerName: 'Dr. Lucas', occurredAt: new Date().toISOString() }];
globalThis.fetch = async (url, init = {}) => {
  if (String(url).includes('/api/v1/address/cep/')) { requests.push(String(url)); return { ok: true, json: async () => String(url).includes('99999999') ? { erro: true } : { cep: '01001-000', logradouro: 'Praça da Sé', bairro: 'Sé', localidade: 'São Paulo', uf: 'SP' } }; }
  const path = new URL(url).pathname.replace('/api/v1', ''); requests.push(path);
  if(path==='/utility/usage')return {ok:true,status:201,json:async()=>({id:'usage',result:'reader_not_configured'})};
  if(path==='/utility/logs')return {ok:true,status:200,json:async()=>({items:[],nextCursor:null})};
  if (path === '/consultations/confirmed-consultation/decision' && init.method === 'POST') { pendingConsultations = []; healthEvents.push({ ...event('confirmed-consultation', 'p1', 'consultation', 'Consulta do Dr. Lucas'), professionSnapshot: 'Médico', payload: { specialty: 'Cardiologia' }, provenance: { source: 'mydoctor_professional' } }); return { ok: true, status: 200, json: async () => ({ id: 'confirmed-consultation', status: 'final' }) }; }
  if (path === '/patients/p1/events' && init.method === 'POST') { const input=JSON.parse(init.body); const saved={...event('home-visit-personal','p1',input.type,input.title),payload:input.payload,organizationNameSnapshot:input.organizationName||null}; healthEvents.push(saved); return {ok:true,status:201,json:async()=>saved}; }
  if (path === '/account' && init.method === 'PUT') account = { ...account, ...JSON.parse(init.body) };
  const data = path === '/consultations/incoming' ? pendingConsultations : path === '/patients/p1/events' ? healthEvents : path === '/account' ? account : path === '/admin/session' ? { authorized: true } : path === '/profiles' ? [{ id: 'p1', name: account.name, source: 'owned', relationship: 'self' }] : ['/professional/profile','/account/document'].includes(path) ? null : [];
  return { ok: true, status: 200, json: async () => data };
};
const outfile = '.navigation-test.cjs';
await build({ entryPoints: ['src/V1ProfessionalShell.tsx'], outfile, bundle: true, platform: 'node', format: 'cjs', jsx: 'automatic', external: ['react', 'react-dom'], define: { 'import.meta.env.DEV': 'false', 'import.meta.env.VITE_API_URL': '""' } });
const Shell = require('../' + outfile).default;
const React = require('react');
const root = createRoot(document.getElementById('root'));
async function settle(work) { await act(async () => { work?.(); await new Promise(resolve => setTimeout(resolve, 15)); }); }
async function click(text) { const button = [...document.querySelectorAll('button')].find(item => item.textContent.trim() === text); assert.ok(button, 'Botão ausente: ' + text); await settle(() => button.click()); }
async function menu() { const button = document.querySelector('button[aria-label="Abrir menu"]'); assert.ok(button); await settle(() => button.click()); }
try {
  await settle(() => root.render(React.createElement(Shell))); await settle();
  assert.match(document.body.textContent, /Olá, Pessoa/);
  const initialDashboard=document.querySelector('[aria-label="Menu do MyDoctor"]');assert.ok(initialDashboard,'Menu de ícones não apareceu após login');
  assert.ok(initialDashboard.querySelector('button svg'),'Ícones não renderizados');
  assert.ok([...initialDashboard.querySelectorAll('button')].some(button=>button.textContent==='Prontuário'));
  assert.equal(window.localStorage.getItem('mydoctor.v1.activeProfileId'), 'p1', 'Paciente lembrado de outra conta foi selecionado');
  await menu();assert.equal([...document.querySelectorAll('button')].some(button=>button.textContent.trim()==='Início'),false);await click('Prontuário');
  assert.match(document.body.textContent, /Atendimento próprio/);
  assert.doesNotMatch(document.body.textContent, /Registro de outra conta|family_history|wellbeing_diary|Atendimento pendente/);
  const filterSection=[...document.querySelectorAll('summary')].find(item=>item.textContent.startsWith('Filtros'));assert.ok(filterSection);assert.equal(filterSection.parentElement.open,false);await settle(()=>filterSection.click());assert.equal(filterSection.parentElement.open,true);
  const rowIds=()=>[...document.querySelectorAll('[data-record-id]')].map(item=>item.dataset.recordId);
  const filter=label=>[...document.querySelectorAll('label')].find(item=>item.textContent.startsWith(label)).querySelector('input,select');
  await settle(()=>document.querySelector('[aria-label="Ordenar por Data/Hora"]').click());
  assert.deepEqual(rowIds(),['old-record','recent-record','own'],'Ordenação por data crescente incorreta');
  await settle(()=>document.querySelector('[aria-label="Ordenar por Data/Hora"]').click());
  assert.equal(rowIds()[0],'own');
  await settle(()=>Simulate.change(document.getElementById('record-filter-text'),{target:{value:'REVISAO'}}));
  assert.equal(rowIds().length,3,'Filtro aplicado antes de acionar o botão');
  await click('Aplicar filtros');
  assert.deepEqual(rowIds(),['recent-record'],'Busca não considerou detalhes sem acentuação');
  await settle(()=>Simulate.change(filter('Filtrar por especialidade'),{target:{value:'Dermatologia'}}));
  await click('Aplicar filtros');
  assert.deepEqual(rowIds(),[],'Filtros não foram combinados');
  await click('Limpar filtros');
  await settle(()=>Simulate.change(filter('Filtrar por profissional'),{target:{value:'Dra. Ana'}}));
  await click('Aplicar filtros');
  assert.deepEqual(rowIds(),['old-record']);
  await click('Limpar filtros');
  await settle(()=>Simulate.change(filter('Data inicial'),{target:{value:'2025-12-09'}}));
  await settle(()=>Simulate.change(filter('Data final'),{target:{value:'2025-12-09'}}));
  await click('Aplicar filtros');
  assert.deepEqual(rowIds(),['old-record'],'Período não incluiu o dia completo');
  await settle(()=>Simulate.change(filter('Data inicial'),{target:{value:'2025-12-10'}}));
  assert.match(document.body.textContent,/data final deve ser igual ou posterior/);
  assert.deepEqual(rowIds(),['old-record'],'Período inválido alterou os resultados');
  assert.equal([...document.querySelectorAll('button')].find(item=>item.textContent==='Aplicar filtros').disabled,true);
  await click('Limpar filtros');
  await settle(()=>filterSection.click());assert.equal(filterSection.parentElement.open,false);
  await settle(()=>document.querySelector('[aria-label="Ordenar por Médico/Atendente"]').click());
  assert.deepEqual(rowIds(),['own','recent-record','old-record']);

  await click('+ Adicionar Atendimento');
  const returnCheckbox=[...document.querySelectorAll('label')].find(label=>label.textContent.includes('Deseja agendar um retorno e receber um alerta?')).querySelector('input');
  await settle(()=>Simulate.change(returnCheckbox,{target:{checked:true}}));
  assert(returnCheckbox.compareDocumentPosition([...document.querySelectorAll('label')].find(label=>label.textContent.startsWith('Observações')).querySelector('textarea'))&window.Node.DOCUMENT_POSITION_PRECEDING,'Retorno ficou antes das observações');
  const returnPeriod=[...document.querySelectorAll('label')].find(label=>label.textContent.startsWith('Prazo para retorno')).querySelector('select');
  const returnDate=[...document.querySelectorAll('label')].find(label=>label.textContent.startsWith('Data/Hora do retorno')).querySelector('input');
  const encounterDate=[...document.querySelectorAll('label')].find(label=>label.textContent.startsWith('Data/Hora (horário local)')).querySelector('input');
  for(const days of ['30','60','90','180']){await settle(()=>Simulate.change(returnPeriod,{target:{value:days}}));const expected=new Date(encounterDate.value);expected.setDate(expected.getDate()+Number(days));assert.equal(new Date(returnDate.value).getTime(),expected.getTime(),'Prazo não manteve horário local');}
  await settle(()=>Simulate.change(returnDate,{target:{value:'2027-05-20T09:45'}}));assert.equal(returnPeriod.value,'custom');
  await click('Cancelar');
  await menu();await click('Acessos à minha digital');await settle();assert.match(document.body.textContent,/Consultar histórico/);assert.ok(!document.querySelector('[aria-label="Captura da digital por foto"]'));assert.ok(!requests.includes('/utility/usage'),'Histórico criou uso de identificação');await click('← Voltar ao MyDoctor');await menu();await click('Identificar Pessoa');await settle();assert.match(document.body.textContent,/Piloto de captura pela câmera/);assert.doesNotMatch(document.querySelector('main:not(.hidden)').textContent,/Consultar histórico|Atualizar histórico/);assert.ok(requests.includes('/utility/usage'),'Acesso à utilidade não registrado');assert.ok([...document.querySelectorAll('button')].some(b=>b.textContent==='Abrir câmera'));assert.equal(document.querySelector('input[capture=environment]').accept,'image/jpeg,image/png,image/webp');await click('← Voltar ao MyDoctor');

  const restoreRequests = requests.filter(path => path === '/account').length;
  await menu();
  const lockedClinicar = [...document.querySelectorAll('button')].find(button => button.textContent.startsWith('Atendimento') && !button.textContent.startsWith('Atendimentos'));
  assert.equal(lockedClinicar?.disabled, true, 'Clinicar disponível para perfil sem validação');
  await click('Meu Diário');
  assert.match(document.body.textContent, /Meu Diário/); assert.doesNotMatch(document.body.textContent, /Olá, Pessoa/);
  await menu(); await click('Histórico familiar');
  assert.doesNotMatch(document.body.textContent, /Olá, Pessoa/);
  await menu(); const professionalMenu=[...document.querySelectorAll('summary')].find(item=>item.textContent==='Profissional'); assert.ok(professionalMenu);
  await settle(()=>professionalMenu.click());
  assert.deepEqual([...document.querySelector('[aria-label="Menu profissional"]').querySelectorAll('button')].map(item=>item.textContent.replace('Aguardando validação','').trim()),['Atendimento','Minha agenda','Solicitar acesso ao prontuário do paciente','Locais que atendo','Validação de cadastro profissional']);
  await click('Validação de cadastro profissional');
  assert.match(document.querySelector('main').textContent, /Dados para validação/);
  assert.equal(document.querySelectorAll('[data-mydoctor-professional-entry]').length, 0, 'Menu depende de mutação externa');
  await click('← Voltar ao MyDoctor');
  assert.doesNotMatch(document.body.textContent, /Olá, Pessoa/);
  await menu(); await click('Meu cadastro');
  assert.match(document.body.textContent, /Você é um profissional da saúde e deseja clinicar pelo APP/);
  assert.equal([...document.querySelectorAll('button')].filter(button => /^Salvar/.test(button.textContent.trim())).length, 1, 'Mais de um botão para salvar');
  assert.match(document.body.textContent, /Endereço completo/);
  assert.match(document.body.textContent, /Foto ou avatar/);assert.match(document.body.textContent,/Digital \(opcional\)/);
  assert.match(document.body.textContent, /CPF \(opcional\)/);
  assert.match(document.body.textContent, /RG \(opcional\)/);
  assert.equal(requests.filter(path => path === '/account').length, restoreRequests + 1, 'Navegação reinicia sessão');
  assert.equal([...document.querySelectorAll('option')].some(option => option.textContent === 'Certidão de nascimento'), false);
  const birthInput = document.querySelector('input[type="date"]');
  await settle(() => Simulate.change(birthInput, { target: { value: '2012-03-12' } }));
  assert.equal([...document.querySelectorAll('option')].some(option => option.textContent === 'Certidão de nascimento'), true);
  await settle(() => Simulate.change(birthInput, { target: { value: '1980-01-01' } }));
  assert.equal([...document.querySelectorAll('option')].some(option => option.textContent === 'Certidão de nascimento'), false);
  const cpfInput = document.getElementById('account-cpf');
  await settle(() => Simulate.change(cpfInput, { target: { value: '52998224725' } }));
  assert.equal(cpfInput.value, '529.982.247-25');
  await settle(() => Simulate.change(cpfInput, { target: { value: '52998224726' } }));
  await settle(() => Simulate.blur(cpfInput));
  assert.match(document.getElementById('error-cpf').textContent, /CPF inválido/);
  await settle(() => Simulate.change(cpfInput, { target: { value: '52998224725' } }));
  const issuer = [...document.querySelectorAll('label')].find(label => label.textContent.startsWith('UF emissora')).querySelector('select');
  await settle(() => Simulate.change(issuer, { target: { value: 'SP' } }));
  const rgInput = document.getElementById('account-rg');
  await settle(() => Simulate.change(rgInput, { target: { value: '119667563' } }));
  assert.equal(rgInput.value, '11.966.756-3');
  await settle(() => Simulate.change(rgInput, { target: { value: '119667564' } }));
  await settle(() => Simulate.blur(rgInput));
  assert.match(document.getElementById('error-rg').textContent, /verificador/);
  await settle(() => Simulate.change(rgInput, { target: { value: '119667563' } }));
  const cepInput = document.querySelector('input[autocomplete="postal-code"]');
  await settle(() => Simulate.change(cepInput, { target: { value: '01001000' } }));
  assert.equal(cepInput.value, '01001-000');
  await act(async () => { await new Promise(resolve => setTimeout(resolve, 400)); });
  assert.equal(document.querySelector('input[autocomplete="address-line1"]').value, 'Praça da Sé');
  assert.equal(document.querySelector('input[autocomplete="address-level2"]').value, 'São Paulo');
  assert.equal(document.querySelector('input[autocomplete="address-line2"]').value, 'Casa');
  assert.equal([...document.querySelectorAll('label')].find(label => label.textContent === 'Número').querySelector('input').value, '42');
  await settle(() => Simulate.change(cepInput, { target: { value: '99999-999' } }));
  await act(async () => { await new Promise(resolve => setTimeout(resolve, 400)); });
  assert.match(document.body.textContent, /CEP não encontrado/);
  assert.equal(document.querySelector('input[autocomplete="address-line1"]').value, 'Praça da Sé');
  await settle(() => Simulate.change(document.querySelector('input[type=checkbox]'), { target: { checked: false } }));
  const phoneInput = document.getElementById('account-phone');
  await settle(() => Simulate.change(phoneInput, { target: { value: '11987654321' } }));
  assert.equal(phoneInput.value, '+55 (11) 98765-4321');
  await click('Salvar cadastro');
  assert.equal(account.phone, '+5511987654321');
  assert.match(document.body.textContent, /Cadastro salvo/);
  assert.equal(account.cpf, '529.982.247-25');
  assert.equal(account.rg, '11.966.756-3');
  assert.equal(account.postalCode, '99999-999');
  await menu();
  assert.equal([...document.querySelectorAll('button')].some(button => button.textContent.startsWith('Atendimento') && !button.textContent.startsWith('Atendimentos')), false, 'Clinicar visível para conta não profissional');
  await click('Atendimentos para confirmar');
  await click('Confirmar e incluir no prontuário');
  assert.match(document.body.textContent, /Atendimento confirmado e incluído no prontuário/);
  await click('← Voltar ao MyDoctor');
  await menu(); await click('Prontuário');
  assert.match(document.body.textContent, /Consulta do Dr. Lucas/, 'Consulta confirmada não apareceu ao voltar para o prontuário');
  const confirmedRecord = [...document.querySelectorAll('details')].find(item => item.textContent.includes('Consulta do Dr. Lucas'));
  assert.ok(confirmedRecord);
  assert.match(confirmedRecord.textContent, /Cardiologia/, 'Especialidade salva não aparece no atendimento profissional');
  assert.equal([...confirmedRecord.querySelectorAll('span,p')].some(item => item.textContent.trim() === 'Médico'), false, 'Profissão exibida como especialidade');
  await click('+ Adicionar Atendimento');
  const clinicalField=label=>[...document.querySelectorAll('label')].find(item=>item.textContent.startsWith(label)).querySelector('input');
  const writesBeforeCancel=requests.filter(path=>path==='/patients/p1/events').length;
  await settle(()=>Simulate.change(clinicalField('Atendimento (descrição)'),{target:{value:'Não salvar'}}));
  await click('Cancelar sem salvar');
  assert.equal(requests.filter(path=>path==='/patients/p1/events').length,writesBeforeCancel,'Cancelar fez requisição de gravação');
  assert.doesNotMatch(document.body.textContent,/Novo Atendimento/);
  await click('+ Adicionar Atendimento');assert.equal(clinicalField('Atendimento (descrição)').value,'');
  await settle(()=>Simulate.change(clinicalField('Atendimento (descrição)'),{target:{value:'Rascunho descartado ao sair'}}));
  await menu();await click('Meu Diário');await menu();await click('Prontuário');
  assert.doesNotMatch(document.body.textContent,/Novo Atendimento/);
  await click('+ Adicionar Atendimento');assert.equal(clinicalField('Atendimento (descrição)').value,'');
  await settle(()=>Simulate.change(clinicalField('Atendimento (descrição)'),{target:{value:'Consulta domiciliar pessoal'}}));
  await settle(()=>Simulate.change(document.querySelector('[aria-label="Modalidade / Tipo de local"]'),{target:{value:'home'}}));
  await click('Salvar Atendimento');
  const savedHome=healthEvents.find(item=>item.id==='home-visit-personal');
  assert.equal(savedHome.patientId,'p1');assert.equal(savedHome.payload.homeVisit,true);assert.equal(savedHome.payload.onlineVisit,false);
  assert.match(document.body.textContent,/Consulta domiciliar pessoal/);
  const personalHome=[...document.querySelectorAll('details')].find(item=>item.textContent.includes('Consulta domiciliar pessoal'));
  assert.match(personalHome.textContent,/Atendimento domiciliar/);
  await menu();
  await click('Sair');
  assert.match(document.body.textContent, /Entrar no MyDoctor/);
  assert.equal(window.sessionStorage.getItem('mydoctor.v1.sessionToken'), null);
  await click('Clique aqui para se cadastrar');
  assert.doesNotMatch(document.body.textContent, /Você é um profissional da saúde e deseja clinicar pelo APP/);
  assert.match(document.body.textContent,/Repita a senha/);
  assert.equal(document.querySelector('[aria-label="Menu do MyDoctor"]'),null,'Menu persistiu após logout');
  await build({ entryPoints: ['src/AccessRequestsPanel.tsx'], outfile: '.consent-test.cjs', bundle: true, platform: 'node', format: 'cjs', jsx: 'automatic', external: ['react'] });
  const ConsentPanel = require('../.consent-test.cjs').default;
  let consent = { id:'request', patientId:'patient', patientName:'Paciente teste', practitionerName:'Médico teste', requesterName:'Médico teste', status:'pending', requestedAt:new Date().toISOString(), registrations:[], requestedPermission:'read_write_consultation', requestedScope:['record'] };
  let decisionArgs; let revoked = false;
  const consentApi = { listIncomingAccessRequests:async()=>[consent], decideAccessRequest:async(...args)=>{ decisionArgs=args; consent={...consent,status:'approved',grantValidUntil:args[4]??null}; return {status:'approved'}; }, revokePatientAccess:async()=>{revoked=true;consent={...consent,status:'revoked'};return {status:'revoked'};} };
  await settle(()=>root.render(React.createElement(ConsentPanel,{api:consentApi})));
  assert.ok([...document.querySelectorAll('button')].some(button=>button.textContent==='Autorizar acesso'));
  const untilInput = document.querySelector('input[type="datetime-local"]');
  await settle(()=>Simulate.change(untilInput,{target:{value:'2000-01-01T00:00'}}));
  await click('Autorizar acesso');assert.match(document.querySelector('[role=alert]').textContent,/futuro/);assert.equal(decisionArgs,undefined);
  await settle(()=>Simulate.change([...document.querySelectorAll('select')].find(select=>[...select.options].some(option=>option.value==='indefinite')),{target:{value:'indefinite'}}));
  await click('Autorizar acesso');assert.equal(decisionArgs[3],'indefinite');assert.equal(decisionArgs[4],undefined);
  assert.match(document.body.textContent,/Tempo indeterminado/);
  window.confirm=()=>true;await click('Revogar acesso');assert.equal(revoked,true);assert.match(document.body.textContent,/Revogado/);
  await fs.unlink('.consent-test.cjs');
  console.log('✅ Navegação: sessão restaurada, telas estáveis, ida/volta profissional, Meu cadastro, flag inicial e logout OK.');
} finally { await settle(() => root.unmount()); await fs.unlink(outfile); dom.window.close(); }



