import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import fs from 'node:fs/promises';
import { build } from 'esbuild';
const require = createRequire(import.meta.url);
const { JSDOM } = require('jsdom');
const { act } = require('react');
const { Simulate } = require('react-dom/test-utils');
const { createRoot } = require('react-dom/client');
const dom = new JSDOM('<div id="root"></div>', { url: 'https://mydoctor.test/' });
for (const key of ['window', 'document', 'navigator', 'MutationObserver', 'HTMLElement', 'HTMLInputElement', 'HTMLTextAreaElement', 'Event', 'CustomEvent']) Object.defineProperty(globalThis, key, { value: dom.window[key], configurable: true });
globalThis.IS_REACT_ACT_ENVIRONMENT = true;
window.sessionStorage.setItem('mydoctor.v1.sessionToken', 'test-session');
let account = { id: 'u1', name: 'Pessoa teste', email: 'teste@mydoctor.test', phone: '', birthDate: '1980-01-01', sex: '', city: '', state: '', completed: true, isHealthProfessional: true, postalCode: '', street: '', neighborhood: '', country: 'Brasil', number: '42', complement: 'Casa' };
let requests = [];
globalThis.fetch = async (url, init = {}) => {
  if (String(url).includes('/api/v1/address/cep/')) { requests.push(String(url)); return { ok: true, json: async () => String(url).includes('99999999') ? { erro: true } : { cep: '01001-000', logradouro: 'Praça da Sé', bairro: 'Sé', localidade: 'São Paulo', uf: 'SP' } }; }
  const path = new URL(url).pathname.replace('/api/v1', ''); requests.push(path);
  if (path === '/account' && init.method === 'PUT') account = { ...account, ...JSON.parse(init.body) };
  const data = path === '/account' ? account : path === '/admin/session' ? { authorized: true } : path === '/profiles' ? [{ id: 'p1', name: account.name, source: 'owned', relationship: 'self' }] : ['/professional/profile','/account/document'].includes(path) ? null : [];
  return { ok: true, status: 200, json: async () => data };
};
const outfile = '.navigation-test.cjs';
await build({ entryPoints: ['src/V1ProfessionalShell.tsx'], outfile, bundle: true, platform: 'node', format: 'cjs', jsx: 'automatic', external: ['react', 'react-dom'], define: { 'import.meta.env.DEV': 'false', 'import.meta.env.VITE_API_URL': '""' } });
const Shell = require('../' + outfile).default;
const React = require('react');
const root = createRoot(document.getElementById('root'));
async function settle(work) { await act(async () => { work?.(); await new Promise(resolve => setTimeout(resolve, 15)); }); }
async function click(text) { const button = [...document.querySelectorAll('button')].find(item => item.textContent.trim() === text); assert.ok(button, 'Botão ausente: ' + text); await settle(() => button.click()); }
async function menu() { const button = document.querySelector('button[aria-label="Abrir menu"]'); assert.ok(button); await settle(() => button.click()); }
try {
  await settle(() => root.render(React.createElement(Shell))); await settle();
  assert.match(document.body.textContent, /Olá, Pessoa/);
  const restoreRequests = requests.filter(path => path === '/account').length;
  await menu();
  const lockedClinicar = [...document.querySelectorAll('button')].find(button => button.textContent.startsWith('Clinicar'));
  assert.equal(lockedClinicar?.disabled, true, 'Clinicar disponível para perfil sem validação');
  await click('Meu Diário');
  assert.match(document.body.textContent, /Meu Diário/); assert.doesNotMatch(document.body.textContent, /Olá, Pessoa/);
  await menu(); await click('Histórico familiar');
  assert.doesNotMatch(document.body.textContent, /Olá, Pessoa/);
  await menu(); await click('Perfil profissional');
  assert.match(document.querySelector('main').textContent, /Dados para validação/);
  assert.equal(document.querySelectorAll('[data-mydoctor-professional-entry]').length, 0, 'Menu depende de mutação externa');
  await click('← Voltar ao MyDoctor');
  assert.doesNotMatch(document.body.textContent, /Olá, Pessoa/);
  await menu(); await click('Meu cadastro');
  assert.match(document.body.textContent, /Você é um profissional da saúde e deseja clinicar pelo APP/);
  assert.equal([...document.querySelectorAll('button')].filter(button => /^Salvar/.test(button.textContent.trim())).length, 1, 'Mais de um botão para salvar');
  assert.match(document.body.textContent, /Endereço completo/);
  assert.match(document.body.textContent, /Foto ou avatar/);
  assert.match(document.body.textContent, /CPF \(opcional\)/);
  assert.match(document.body.textContent, /RG \(opcional\)/);
  assert.equal(requests.filter(path => path === '/account').length, restoreRequests + 1, 'Navegação reinicia sessão');
  assert.equal([...document.querySelectorAll('option')].some(option => option.textContent === 'Certidão de nascimento'), false);
  const birthInput = document.querySelector('input[type="date"]');
  await settle(() => Simulate.change(birthInput, { target: { value: '2012-03-12' } }));
  assert.equal([...document.querySelectorAll('option')].some(option => option.textContent === 'Certidão de nascimento'), true);
  await settle(() => Simulate.change(birthInput, { target: { value: '1980-01-01' } }));
  assert.equal([...document.querySelectorAll('option')].some(option => option.textContent === 'Certidão de nascimento'), false);
  const cpfInput = document.getElementById('account-cpf');
  await settle(() => Simulate.change(cpfInput, { target: { value: '52998224725' } }));
  assert.equal(cpfInput.value, '529.982.247-25');
  await settle(() => Simulate.change(cpfInput, { target: { value: '52998224726' } }));
  await settle(() => Simulate.blur(cpfInput));
  assert.match(document.getElementById('error-cpf').textContent, /CPF inválido/);
  await settle(() => Simulate.change(cpfInput, { target: { value: '52998224725' } }));
  const issuer = [...document.querySelectorAll('label')].find(label => label.textContent.startsWith('UF emissora')).querySelector('select');
  await settle(() => Simulate.change(issuer, { target: { value: 'SP' } }));
  const rgInput = document.getElementById('account-rg');
  await settle(() => Simulate.change(rgInput, { target: { value: '119667563' } }));
  assert.equal(rgInput.value, '11.966.756-3');
  await settle(() => Simulate.change(rgInput, { target: { value: '119667564' } }));
  await settle(() => Simulate.blur(rgInput));
  assert.match(document.getElementById('error-rg').textContent, /verificador/);
  await settle(() => Simulate.change(rgInput, { target: { value: '119667563' } }));
  const cepInput = document.querySelector('input[autocomplete="postal-code"]');
  await settle(() => Simulate.change(cepInput, { target: { value: '01001000' } }));
  assert.equal(cepInput.value, '01001-000');
  await act(async () => { await new Promise(resolve => setTimeout(resolve, 400)); });
  assert.equal(document.querySelector('input[autocomplete="address-line1"]').value, 'Praça da Sé');
  assert.equal(document.querySelector('input[autocomplete="address-level2"]').value, 'São Paulo');
  assert.equal(document.querySelector('input[autocomplete="address-line2"]').value, 'Casa');
  assert.equal([...document.querySelectorAll('label')].find(label => label.textContent === 'Número').querySelector('input').value, '42');
  await settle(() => Simulate.change(cepInput, { target: { value: '99999-999' } }));
  await act(async () => { await new Promise(resolve => setTimeout(resolve, 400)); });
  assert.match(document.body.textContent, /CEP não encontrado/);
  assert.equal(document.querySelector('input[autocomplete="address-line1"]').value, 'Praça da Sé');
  await settle(() => Simulate.change(document.querySelector('input[type=checkbox]'), { target: { checked: false } }));
  const phoneInput = document.getElementById('account-phone');
  await settle(() => Simulate.change(phoneInput, { target: { value: '11987654321' } }));
  assert.equal(phoneInput.value, '+55 (11) 98765-4321');
  await click('Salvar cadastro');
  assert.equal(account.phone, '+5511987654321');
  assert.match(document.body.textContent, /Cadastro salvo/);
  assert.equal(account.cpf, '529.982.247-25');
  assert.equal(account.rg, '11.966.756-3');
  assert.equal(account.postalCode, '99999-999');
  await menu();
  assert.equal([...document.querySelectorAll('button')].some(button => button.textContent.startsWith('Clinicar')), false, 'Clinicar visível para conta não profissional');
  await click('Sair');
  assert.match(document.body.textContent, /Entrar no MyDoctor/);
  assert.equal(window.sessionStorage.getItem('mydoctor.v1.sessionToken'), null);
  await click('Clique aqui para se cadastrar');
  assert.match(document.body.textContent, /Você é um profissional da saúde e deseja clinicar pelo APP/);
  await build({ entryPoints: ['src/AccessRequestsPanel.tsx'], outfile: '.consent-test.cjs', bundle: true, platform: 'node', format: 'cjs', jsx: 'automatic', external: ['react'] });
  const ConsentPanel = require('../.consent-test.cjs').default;
  let consent = { id:'request', patientId:'patient', patientName:'Paciente teste', practitionerName:'Médico teste', requesterName:'Médico teste', status:'pending', requestedAt:new Date().toISOString(), registrations:[], requestedPermission:'read_write_consultation', requestedScope:['record'] };
  let decisionArgs; let revoked = false;
  const consentApi = { listIncomingAccessRequests:async()=>[consent], decideAccessRequest:async(...args)=>{ decisionArgs=args; consent={...consent,status:'approved',grantValidUntil:args[4]??null}; return {status:'approved'}; }, revokePatientAccess:async()=>{revoked=true;consent={...consent,status:'revoked'};return {status:'revoked'};} };
  await settle(()=>root.render(React.createElement(ConsentPanel,{api:consentApi})));
  assert.ok([...document.querySelectorAll('button')].some(button=>button.textContent==='Autorizar acesso'));
  const untilInput = document.querySelector('input[type="datetime-local"]');
  await settle(()=>Simulate.change(untilInput,{target:{value:'2000-01-01T00:00'}}));
  await click('Autorizar acesso');assert.match(document.querySelector('[role=alert]').textContent,/futuro/);assert.equal(decisionArgs,undefined);
  await settle(()=>Simulate.change(document.querySelector('select'),{target:{value:'indefinite'}}));
  await click('Autorizar acesso');assert.equal(decisionArgs[3],'indefinite');assert.equal(decisionArgs[4],undefined);
  assert.match(document.body.textContent,/Tempo indeterminado/);
  window.confirm=()=>true;await click('Revogar acesso');assert.equal(revoked,true);assert.match(document.body.textContent,/Revogado/);
  await fs.unlink('.consent-test.cjs');
  console.log('✅ Navegação: sessão restaurada, telas estáveis, ida/volta profissional, Meu cadastro, flag inicial e logout OK.');
} finally { await settle(() => root.unmount()); await fs.unlink(outfile); dom.window.close(); }



