import { useEffect, useRef, useState } from 'react';
import FingerprintPhotoCapture from './components/FingerprintPhotoCapture';
import { Fingerprint } from 'lucide-react';
import type { MyDoctorV1Api, UtilityLocation, UtilityPhotoAction, UtilityPhotoDiagnostic } from './lib/api-v1';
export function locate():Promise<UtilityLocation>{return new Promise(resolve=>{const timer=window.setTimeout(()=>resolve({status:'timeout'}),12000);const done=(value:UtilityLocation)=>{window.clearTimeout(timer);resolve(value)};if(!navigator.geolocation)return done({status:'unavailable'});try{navigator.geolocation.getCurrentPosition(p=>done({status:'obtained',latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy}),e=>done({status:e.code===1?'denied':e.code===3?'timeout':'error'}),{enableHighAccuracy:true,timeout:10000,maximumAge:0})}catch{done({status:'error'})}})}
export default function PublicUtilityPanel({api}:{api:MyDoctorV1Api}){
  const [error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(true);
  const opening=useRef<Promise<unknown>|null>(null);
  useEffect(()=>{let current=true;if(!opening.current)opening.current=locate().then(location=>api.recordUtilityUsage('open',location));opening.current.then(()=>{if(current){setBusy(false)}}).catch(e=>{if(current){setBusy(false);setError('Não foi possível registrar o uso: '+e.message)}});return()=>{current=false}},[api]);
  async function photoAudit(action:UtilityPhotoAction,diagnostic?:UtilityPhotoDiagnostic){await api.recordUtilityUsage('finger_photo',await locate(),action,diagnostic);if(action==='photo_captured')setMessage('Captura registrada. A foto permanece apenas no aparelho. Nenhuma pessoa foi identificada.');else if(action==='photo_discarded')setMessage('Foto descartada. O histórico da tentativa foi preservado.')}
  return <div className="space-y-4"><section className="rounded-2xl border border-line bg-white p-4 sm:p-5"><div className="flex items-start gap-3"><Fingerprint aria-hidden="true" className="h-8 w-8 shrink-0 text-moss-700"/><div><h2 className="text-lg font-bold text-ink">Digital por fotografia</h2><p className="mt-1 text-sm text-mute">Para apoiar pessoas desorientadas, sem memória ou em situação de vulnerabilidade.</p></div></div><p className="mt-4 rounded-xl bg-paper p-3 text-sm text-ink">Piloto de captura pela câmera do celular. Você pode fotografar e conferir a digital. O cadastro da referência e a identificação automática ainda dependem do motor biométrico. Nenhuma identificação será confirmada nesta etapa.</p><p className="mt-3 text-xs text-mute">O acesso e cada tentativa são registrados com seu usuário e horário. Autorize a localização para incluir coordenadas e precisão. Se não estiver disponível, o log registra o motivo.</p>{busy?<p role="status" className="mt-4 text-sm text-mute">Registrando acesso e localização…</p>:<FingerprintPhotoCapture onAudit={photoAudit}/>}</section>{error&&<p role="alert" className="rounded-xl border border-danger-600 bg-white p-3 text-sm text-danger-600">{error}</p>}{message&&<p role="status" className="rounded-xl bg-moss-50 p-3 text-sm text-moss-800">{message}</p>}</div>;
}
